/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOSoftware;
import com.mycompany.transporte_mercancia.Logica.Software;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ebisu
 */
public class FmrSoftware extends javax.swing.JInternalFrame {

    DAOSoftware dao = new DAOSoftware();

    /**
     * Creates new form FmrSoftware
     */
    public FmrSoftware() {
        initComponents();
        limpiarFormulario();
        cargarTabla();
        activarModoNuevo();
        txt_version.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isLetterOrDigit(c) && c != '.') {
                    evt.consume(); // bloquea el carácter inválido en tiempo real
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_software = new javax.swing.JTable();
        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_version = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_fabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tbl_software.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_software.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_softwareMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_software);

        bt_agregar.setText("Agregar");
        bt_agregar.addActionListener(this::bt_agregarActionPerformed);

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(this::bt_modificarActionPerformed);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(this::bt_eliminarActionPerformed);

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(this::bt_cancelarActionPerformed);

        jLabel1.setText("Nombre");

        jLabel2.setText("Version");

        jLabel3.setText("Fabricante");

        jLabel4.setText("ID");

        txt_id.setEditable(false);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("X");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("🔄");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_version, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jLabel4)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txt_id)
                                                    .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                        .addComponent(txt_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bt_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_agregar)
                            .addComponent(bt_modificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cancelar)
                            .addComponent(bt_eliminar))
                        .addGap(129, 129, 129))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        String nombre = txt_nombre.getText().trim();
        String version = txt_version.getText().trim();
        String fabricante = txt_fabricante.getText().trim();

        if (!validarCampos(nombre, version, fabricante)) {
            return;
        }

        if (dao.existeSoftware(nombre, version)) {
            JOptionPane.showMessageDialog(this, "Ya existe un software con ese nombre y versión.");
            txt_nombre.requestFocus();
            return;
        }

        Software s = new Software();
        s.setNombre(nombre);
        s.setVersion(version);
        s.setFabricante(fabricante);

        dao.create(s);
        JOptionPane.showMessageDialog(this, "Software registrado correctamente.");
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void activarModoNuevo() {

        bt_agregar.setEnabled(true);
        bt_modificar.setEnabled(false);
        bt_eliminar.setEnabled(false);
    }

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        if (txt_id.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un software de la tabla para modificar.");
            return;
        }

        int id = Integer.parseInt(txt_id.getText().trim());

        String nombre = txt_nombre.getText().trim();
        String version = txt_version.getText().trim();
        String fabricante = txt_fabricante.getText().trim();

        if (!validarCampos(nombre, version, fabricante)) {
            return;
        }

        if (dao.existeSoftware(nombre, version, id)) {
            JOptionPane.showMessageDialog(this, "Ya existe otro software con ese nombre y versión.");
            txt_nombre.requestFocus();
            return;
        }

        Software s = new Software();
        s.setIdSoftware(id);
        s.setNombre(nombre);
        s.setVersion(version);
        s.setFabricante(fabricante);

        dao.update(s);
        JOptionPane.showMessageDialog(this, "Software modificado correctamente.");
        cargarTabla();
        activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
        activarModoNuevo();
        tbl_software.clearSelection();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void limpiarFormulario() {

        txt_id.setText("");
        txt_nombre.setText("");
        txt_version.setText("");
        txt_fabricante.setText("");
    }

    public void cargarTabla() {

        Object columnas[] = {"ID", "Nombre", "Version", "Fabricante", "Fecha Registro"};
        DefaultTableModel modelo
                = new DefaultTableModel(columnas, 0);
        for (Software s : dao.listarTodos()) {
            Object fila[] = {s.getIdSoftware(), s.getNombre(), s.getVersion(), s.getFabricante(), s.getFechaRegistro()};
            modelo.addRow(fila);
        }
        tbl_software.setModel(modelo);
    }


    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        // TODO add your handling code here:
        int id
                = Integer.parseInt(txt_id.getText());
        dao.delete(id);
        JOptionPane.showMessageDialog(this,
                "Software eliminado correctamente");

        cargarTabla();
        activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void tbl_softwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_softwareMouseClicked
        int fila = tbl_software.getSelectedRow();

        if (fila != -1) {

            txt_id.setText(
                    tbl_software.getValueAt(fila, 0).toString());

            txt_nombre.setText(
                    tbl_software.getValueAt(fila, 1).toString());

            txt_version.setText(
                    tbl_software.getValueAt(fila, 2).toString());

            txt_fabricante.setText(
                    tbl_software.getValueAt(fila, 3).toString());

            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_softwareMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    cargarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void activarModoEditar() {
        bt_agregar.setEnabled(false);
        bt_modificar.setEnabled(true);
        bt_eliminar.setEnabled(true);
    }

    private boolean validarCampos(String nombre, String version, String fabricante) {
        // --- NOMBRE ---
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
            txt_nombre.requestFocus();
            return false;
        }
        if (nombre.length() < 2) {
            JOptionPane.showMessageDialog(this, "El nombre debe tener al menos 2 caracteres.");
            txt_nombre.requestFocus();
            return false;
        }
        if (nombre.length() > 100) {
            JOptionPane.showMessageDialog(this, "El nombre no puede superar los 100 caracteres.");
            txt_nombre.requestFocus();
            return false;
        }

        // --- VERSION ---
        if (version.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La versión no puede estar vacía.");
            txt_version.requestFocus();
            return false;
        }
        if (!version.matches("[A-Za-z0-9.]+")) {
            JOptionPane.showMessageDialog(this, "La versión solo puede contener letras, números y puntos.\nEjemplo: 1.0, 2.3.1, v10.2");
            txt_version.requestFocus();
            return false;
        }
        if (version.length() > 20) {
            JOptionPane.showMessageDialog(this, "La versión no puede superar los 20 caracteres.");
            txt_version.requestFocus();
            return false;
        }

        // --- FABRICANTE ---
        if (fabricante.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El fabricante no puede estar vacío.");
            txt_fabricante.requestFocus();
            return false;
        }
        if (fabricante.length() < 2) {
            JOptionPane.showMessageDialog(this, "El fabricante debe tener al menos 2 caracteres.");
            txt_fabricante.requestFocus();
            return false;
        }
        if (fabricante.length() > 100) {
            JOptionPane.showMessageDialog(this, "El fabricante no puede superar los 100 caracteres.");
            txt_fabricante.requestFocus();
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_software;
    private javax.swing.JTextField txt_fabricante;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_version;
    // End of variables declaration//GEN-END:variables
}
