/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOSoftware;
import com.mycompany.transporte_mercancia.Data.DAOSoftwareEquipo;
import com.mycompany.transporte_mercancia.Data.DAOEquipoOficina;

import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.mycompany.transporte_mercancia.Logica.Software;
import com.mycompany.transporte_mercancia.Logica.EquipoOficina;
import com.mycompany.transporte_mercancia.Logica.SoftwareEquipo;

/**
 *
 * @author saave
 */
public class FrmAsignarSoftware extends javax.swing.JInternalFrame {

    private DAOSoftwareEquipo dao = new DAOSoftwareEquipo();
    private DAOSoftware daoSoftware = new DAOSoftware();
    private DAOEquipoOficina daoEquipo = new DAOEquipoOficina();
    private int idSeleccionado = 0;

    /**
     * Creates new form FrmAsignarSoftware
     */
    public FrmAsignarSoftware() {
        initComponents();
        aplicarEstilos();
        cargarSoftware();
        cargarEquipos();
        cargarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_software = new javax.swing.JComboBox<>();
        cb_equipo = new javax.swing.JComboBox<>();
        cb_estado = new javax.swing.JComboBox<>();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_asignaciones = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        jLabel1.setText("Software");

        jLabel2.setText("Equipo de oficina");

        jLabel3.setText("Fecha");

        jLabel4.setText("Estado");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));

        bt_agregar.setText("Asignar");
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        tbl_asignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_asignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_asignacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_asignaciones);

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("🔄");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel4))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(cb_equipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_software, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_eliminar)
                                    .addComponent(bt_agregar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_modificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_cancelar, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cb_software, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_agregar)
                            .addComponent(bt_modificar))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar))))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed

        Software software = (Software) cb_software.getSelectedItem();
        EquipoOficina equipo = (EquipoOficina) cb_equipo.getSelectedItem();

        String estado = cb_estado.getSelectedItem().toString();

        if (dc_fecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha");
            return;
        }
        Date fecha = new Date(dc_fecha.getDate().getTime());

        if (dao.existeRelacion(
                software.getIdSoftware(),
                equipo.getIdEquipo())) {

            JOptionPane.showMessageDialog(this,
                    "La asignación ya existe");
            return;
        }

        SoftwareEquipo se = new SoftwareEquipo();

        se.setSoftware(software);
        se.setEquipo(equipo);
        se.setFechaInstalacion(fecha);
        se.setEstado(estado);

        dao.create(se);

        JOptionPane.showMessageDialog(this,
                "Software asignado correctamente");

        cargarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        if (idSeleccionado == 0) {

            JOptionPane.showMessageDialog(this,
                    "Seleccione una asignación");

            return;
        }

        String estado = cb_estado.getSelectedItem().toString();

        if (dc_fecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha");
            return;
        }
        Date fecha = new Date(dc_fecha.getDate().getTime());

        Software software = (Software) cb_software.getSelectedItem();

        EquipoOficina equipo
                = (EquipoOficina) cb_equipo.getSelectedItem();

        SoftwareEquipo se = new SoftwareEquipo();

        se.setIdSoftwareEquipo(idSeleccionado);

        se.setSoftware(software);

        se.setEquipo(equipo);

        se.setFechaInstalacion(fecha);

        se.setEstado(estado);

        dao.update(se);

        JOptionPane.showMessageDialog(this,
                "Asignación modificada");

        cargarTabla();
        activarModoNuevo();
        limpiarFormulario();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_modificarActionPerformed
    private void cargarEquipos() {

        cb_equipo.removeAllItems();

        ArrayList<EquipoOficina> lista = daoEquipo.listarTodos();
        for (EquipoOficina e : lista) {
            cb_equipo.addItem(e);
        }
    }

    private void cargarSoftware() {

        cb_software.removeAllItems();
        ArrayList<Software> lista = daoSoftware.listarTodos();
        for (Software s : lista) {
            cb_software.addItem(s);
        }
    }

    private void cargarTabla() {

        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("ID");
        modelo.addColumn("Software");
        modelo.addColumn("Equipo");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estado");

        ArrayList<SoftwareEquipo> lista = dao.listarTodos();

        for (SoftwareEquipo se : lista) {

            Object[] fila = {
                se.getIdSoftwareEquipo(),
                se.getSoftware().getNombre(),
                se.getEquipo().getNumeroSerie(),
                se.getFechaInstalacion(),
                se.getEstado()
            };

            modelo.addRow(fila);
        }

        tbl_asignaciones.setModel(modelo);
    }

    private void limpiarFormulario() {

        dc_fecha.setDate(null);

        cb_estado.setSelectedIndex(0);

        cb_software.setSelectedIndex(0);

        cb_equipo.setSelectedIndex(0);

        tbl_asignaciones.clearSelection();

        idSeleccionado = 0;
    }
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        // Accion de Eliminar //
        int fila = tbl_asignaciones.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una fila");
            return;
        }

        int id = Integer.parseInt(
                tbl_asignaciones.getValueAt(fila, 0).toString());

        dao.delete(id);

        JOptionPane.showMessageDialog(this,
                "Asignación eliminada");
        
        cargarTabla();        // TODO add your handling code here:
       activarModoNuevo();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();        // TODO add your handling code here:
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void tbl_asignacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_asignacionesMouseClicked
         int fila = tbl_asignaciones.getSelectedRow();
    if (fila == -1) return;  // ← guarda extra por si acaso

    idSeleccionado = Integer.parseInt(
            tbl_asignaciones.getValueAt(fila, 0).toString());

    // ── Cargar fecha ────────────────────────────────────────────────────
    Object fechaObj = tbl_asignaciones.getValueAt(fila, 3);
    if (fechaObj != null) {
        try {
            dc_fecha.setDate(java.sql.Date.valueOf(fechaObj.toString()));
        } catch (Exception e) {
            dc_fecha.setDate(null);
        }
    }

    // ── Cargar estado ───────────────────────────────────────────────────
    String estado = tbl_asignaciones.getValueAt(fila, 4).toString();
    cb_estado.setSelectedItem(estado);

    // ── Cargar Software (buscar objeto por nombre) ──────────────────────
    String nombreSoftware = tbl_asignaciones.getValueAt(fila, 1).toString();
    for (int i = 0; i < cb_software.getItemCount(); i++) {
        Software s = cb_software.getItemAt(i);
        if (s.getNombre().equals(nombreSoftware)) {
            cb_software.setSelectedIndex(i);
            break;
        }
    }

    // ── Cargar Equipo (buscar objeto por número de serie) ───────────────
    String serieEquipo = tbl_asignaciones.getValueAt(fila, 2).toString();
    for (int i = 0; i < cb_equipo.getItemCount(); i++) {
        EquipoOficina e = cb_equipo.getItemAt(i);
        if (e.getNumeroSerie().equals(serieEquipo)) {
            cb_equipo.setSelectedIndex(i);
            break;
        }
    }

    activarModoEditar();          // TODO add your handling code here:
    }//GEN-LAST:event_tbl_asignacionesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 private void activarModoEditar() {
        this.bt_cancelar.setEnabled(true);
        this.bt_modificar.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_agregar.setEnabled(false);
    }

    /**
     * Activa el modo nuevo para ingresar un equipo.
     */
    private void activarModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_modificar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_agregar.setEnabled(true);
    }
    
     private void aplicarEstilos() {

        // ── Paleta Deep Ocean ────────────────────────────────────────────────
        java.awt.Color BG_DARK   = new java.awt.Color(0x0A192F);
        java.awt.Color BG_MID    = new java.awt.Color(0x172A45);
        java.awt.Color BG_FIELD  = new java.awt.Color(0x1F3460);
        java.awt.Color MINT      = new java.awt.Color(0x64FFDA);
        java.awt.Color CYAN      = new java.awt.Color(0x57CBF2);
        java.awt.Color CORAL     = new java.awt.Color(0xFF6B6B);
        java.awt.Color GRAY_BTN  = new java.awt.Color(0x8892B0);
        java.awt.Color TEXT_MAIN = new java.awt.Color(0xCCD6F6);
        java.awt.Color ROW_ALT   = new java.awt.Color(0x112240);

        // ── Fuentes ──────────────────────────────────────────────────────────
        java.awt.Font FONT_LABEL = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
        java.awt.Font FONT_FIELD = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Font FONT_BTN   = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);

        // ── Panel principal ──────────────────────────────────────────────────
        getContentPane().setBackground(BG_DARK);
        setTitle("🖥️  Asignar Software a Equipo");
        setBackground(BG_MID);

        // ── Labels ───────────────────────────────────────────────────────────
        javax.swing.JLabel[] labels = { jLabel1, jLabel2, jLabel3, jLabel4 };
        for (javax.swing.JLabel lbl : labels) {
            if (lbl != null) {
                lbl.setForeground(TEXT_MAIN);
                lbl.setFont(FONT_LABEL);
            }
        }

        // ── ComboBoxes ───────────────────────────────────────────────────────
        javax.swing.JComboBox<?>[] combos = { cb_software, cb_equipo, cb_estado };
        for (javax.swing.JComboBox<?> cb : combos) {
            if (cb != null) {
                cb.setBackground(BG_FIELD);
                cb.setForeground(TEXT_MAIN);
                cb.setFont(FONT_FIELD);
                cb.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(MINT, 1, true),
                    javax.swing.BorderFactory.createEmptyBorder(2, 6, 2, 6)
                ));
                // Renderer del combo
                cb.setRenderer(new javax.swing.DefaultListCellRenderer() {
                    @Override
                    public java.awt.Component getListCellRendererComponent(
                            javax.swing.JList<?> list, Object value,
                            int index, boolean isSelected, boolean cellHasFocus) {
                        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                        setBackground(isSelected ? MINT : BG_FIELD);
                        setForeground(isSelected ? BG_DARK : TEXT_MAIN);
                        setFont(FONT_FIELD);
                        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
                        return this;
                    }
                });
            }
        }

        // ── JDateChooser — estilo Deep Ocean ─────────────────────────────────
        // dc_fecha es com.toedter.calendar.JDateChooser
        if (dc_fecha != null) {
            dc_fecha.setBackground(BG_FIELD);
            dc_fecha.setForeground(TEXT_MAIN);
            dc_fecha.setFont(FONT_FIELD);
            dc_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(MINT, 1, true));

            // El campo de texto interno del DateChooser
            if (dc_fecha.getDateEditor() != null &&
                dc_fecha.getDateEditor().getUiComponent() instanceof javax.swing.JTextField) {
                javax.swing.JTextField dtf =
                    (javax.swing.JTextField) dc_fecha.getDateEditor().getUiComponent();
                dtf.setBackground(BG_FIELD);
                dtf.setForeground(TEXT_MAIN);
                dtf.setCaretColor(MINT);
                dtf.setFont(FONT_FIELD);
                dtf.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
            }

            // Botón del calendario
            java.awt.Component[] comps = dc_fecha.getComponents();
            for (java.awt.Component comp : comps) {
                if (comp instanceof javax.swing.JButton) {
                    javax.swing.JButton calBtn = (javax.swing.JButton) comp;
                    calBtn.setBackground(CYAN);
                    calBtn.setForeground(BG_DARK);
                    calBtn.setFocusPainted(false);
                    calBtn.setBorderPainted(false);
                    calBtn.setOpaque(true);
                }
            }
        }

        // ── ToolBar ──────────────────────────────────────────────────────────
        if (jToolBar1 != null) {
            jToolBar1.setBackground(BG_MID);
            jToolBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(
                0, 0, 1, 0, new java.awt.Color(0x1F3460)));
        }

        // ── Botones con código de color ───────────────────────────────────────
        estilizarBoton(bt_agregar,   MINT,     BG_DARK,  "+ Asignar",    FONT_BTN);
        estilizarBoton(bt_modificar, CYAN,     BG_DARK,  "# Modificar",   FONT_BTN);
        estilizarBoton(bt_eliminar,  CORAL,    BG_DARK,  "X Eliminar",    FONT_BTN);
        estilizarBoton(bt_cancelar,  GRAY_BTN, BG_DARK,  "* Cancelar",    FONT_BTN);
        estilizarBoton(jButton2,     CYAN,     BG_DARK,  "🔄 Actualizar",  FONT_BTN);
        estilizarBoton(jButton1,     CORAL,    BG_DARK,  "X Cerrar",      FONT_BTN);

        // ── Tabla ────────────────────────────────────────────────────────────
        tbl_asignaciones.setBackground(BG_MID);
        tbl_asignaciones.setForeground(TEXT_MAIN);
        tbl_asignaciones.setFont(FONT_FIELD);
        tbl_asignaciones.setRowHeight(26);
        tbl_asignaciones.setGridColor(new java.awt.Color(0x1F3460));
        tbl_asignaciones.setSelectionBackground(MINT);
        tbl_asignaciones.setSelectionForeground(BG_DARK);
        tbl_asignaciones.setShowHorizontalLines(true);
        tbl_asignaciones.setShowVerticalLines(false);

        // Cabecera de tabla
        javax.swing.table.JTableHeader header = tbl_asignaciones.getTableHeader();
        header.setBackground(BG_MID);
        header.setForeground(MINT);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Renderer con filas alternas
        tbl_asignaciones.setDefaultRenderer(Object.class,
            new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int column) {
                    super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    if (isSelected) {
                        setBackground(MINT);
                        setForeground(BG_DARK);
                    } else {
                        setBackground(row % 2 == 0 ? BG_MID : ROW_ALT);
                        setForeground(TEXT_MAIN);
                    }
                    setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
                    return this;
                }
            }
        );

        // ── ScrollPane ───────────────────────────────────────────────────────
        jScrollPane1.setBackground(BG_DARK);
        jScrollPane1.getViewport().setBackground(BG_MID);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(0x1F3460), 1));
    }

    /**
     * Aplica estilo visual uniforme a un JButton.
     */
    private void estilizarBoton(javax.swing.JButton btn,
                                java.awt.Color bg,
                                java.awt.Color fg,
                                String texto,
                                java.awt.Font fuente) {
        if (btn == null) return;
        btn.setText(texto);
        btn.setBackground(bg);
        btn.setForeground(fg);
        btn.setFont(fuente);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(bg.darker(), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(6, 14, 6, 14)
        ));
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(bg.brighter());
            }
            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(bg);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JComboBox<EquipoOficina> cb_equipo;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<Software> cb_software;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_asignaciones;
    // End of variables declaration//GEN-END:variables
}
