/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOPersonal;
import com.mycompany.transporte_mercancia.Logica.Personal;
import com.mycompany.transporte_mercancia.Data.DAOCamion;
import com.mycompany.transporte_mercancia.Logica.Camion;
import javax.swing.table.DefaultTableModel;

import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author saave
 */
public class FrmCamiones extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCamiones
     */
    public FrmCamiones() {
        initComponents();
        cargarTabla();
        cargarComboConductores();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_guardar_cambios = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_camiones = new javax.swing.JTable();
        bt_guardar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        cmb_conductor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txt_id_camion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_matricula = new javax.swing.JTextField();
        cmb_modelo = new javax.swing.JComboBox<>();
        bt_cerrar_pestaña = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        bt_guardar_cambios.setText("Guardar Cambios");
        bt_guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardar_cambiosActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Modelo");

        jLabel2.setText("Marca");

        jLabel3.setText("Año");

        jLabel4.setText("Asignar Conductor");

        tbl_camiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_camiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_camionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_camiones);

        bt_guardar.setText("Guardar");
        bt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        txt_id_camion.setEditable(false);

        jLabel6.setText("Matricula");

        cmb_modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Liviano", "Pesado" }));

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");

        jLabel7.setText("-- LFCS84 --");

        jLabel8.setText("Ejemplo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_actualizar_pestaña))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_conductor, 0, 124, Short.MAX_VALUE)
                                    .addComponent(txt_anio)
                                    .addComponent(txt_marca)
                                    .addComponent(txt_id_camion)
                                    .addComponent(txt_matricula)
                                    .addComponent(cmb_modelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(bt_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_guardar_cambios)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(bt_cerrar_pestaña)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_id_camion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmb_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_guardar_cambios)
                            .addComponent(bt_guardar))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cerrar_pestaña)
                            .addComponent(bt_actualizar_pestaña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento del botón "Cancelar". Limpia todos los campos del
     * formulario llamando a {@link #limpiarFormulario()}.
     *
     * @param evt Evento de acción generado por el botón bt_cancelar.
     */
    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    /**
     * Limpia todos los campos de entrada del formulario de camiones,
     * restableciendo los textos a vacío y el combo de conductores a sin
     * selección.
     */
    private void limpiarFormulario() {
        this.txt_anio.setText("");
        this.cmb_conductor.setSelectedItem("");
        this.txt_marca.setText("");
        this.cmb_modelo.setSelectedIndex(0);
        this.txt_id_camion.setText("");
        this.txt_matricula.setText("");
    }

    /**
     * Valida que la matrícula tenga el formato chileno correcto.
     * <ul>
     * <li>Formato antiguo: 2 letras + 4 dígitos → ej. AB1234</li>
     * <li>Formato nuevo: 4 letras + 2 dígitos → ej. ABCD12</li>
     * </ul>
     * Se acepta con o sin guion (AB-1234 / ABCD-12).
     *
     * @param matricula texto ingresado por el usuario.
     * @return {@code true} si el formato es válido; {@code false} en caso
     * contrario.
     */
    private boolean validarFormatoMatricula(String matricula) {
        if (matricula == null) {
            return false;
        }
        // Normalizar: mayúsculas y quitar guion
        String m = matricula.toUpperCase().replace("-", "").trim();
        return m.matches("^[A-Z]{2}[0-9]{4}$") // Formato antiguo: AB1234
                || m.matches("^[A-Z]{4}[0-9]{2}$");   // Formato nuevo:  ABCD12
    }

    /**
     * Normaliza la matrícula a mayúsculas sin guion.
     */
    private String normalizarMatricula(String matricula) {
        return matricula.toUpperCase().replace("-", "").trim();
    }

    /**
     * Carga el combo box {@code cmb_conductor} con todos los conductores
     * disponibles en el sistema, consultando el {@link DAOPersonal} filtrado
     * por el rol "conductor". Elimina los ítems previos antes de cargar los
     * nuevos.
     */
    public void cargarComboConductores() {
        cmb_conductor.removeAllItems();
        for (Personal p : daoPersonal.listarPorRol("conductor")) {
            cmb_conductor.addItem(p);
        }
    }

    /**
     * Maneja el evento del botón "Guardar". Registra un nuevo camión en el
     * sistema con los datos ingresados en el formulario.
     * <p>
     * Realiza las siguientes validaciones y operaciones:
     * <ul>
     * <li>Verifica que la matrícula no exista previamente en la BD.</li>
     * <li>Inicializa el kilometraje total en 0 si es {@code null}.</li>
     * <li>Persiste el camión usando {@link DAOCamion#create(Camion)}.</li>
     * <li>Recarga la tabla y el combo de conductores.</li>
     * <li>Limpia el formulario tras el registro exitoso.</li>
     * </ul>
     *
     * @param evt Evento de acción generado por el botón bt_guardar.
     */

    private void bt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardarActionPerformed
        String matriculaRaw = txt_matricula.getText().trim();

        // ── Validación año ──────────────────────────────────────────────────
        int anio;
        try {
            anio = Integer.parseInt(txt_anio.getText().trim());
            if (anio <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El año debe ser un número positivo.",
                        "Año inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El año ingresado no es válido. Ingrese solo números.",
                    "Año inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Validación formato matrícula ────────────────────────────────────
        if (!validarFormatoMatricula(matriculaRaw)) {
            JOptionPane.showMessageDialog(this,
                    "Formato de matrícula inválido.\n"
                    + "Use el formato antiguo (AB1234) o nuevo (ABCD12).\n"
                    + "El guion es opcional.",
                    "Matrícula inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String matriculaNormalizada = normalizarMatricula(matriculaRaw);

        // ── Validación duplicado ────────────────────────────────────────────
        if (dp.existeMatricula(matriculaNormalizada)) {
            JOptionPane.showMessageDialog(this,
                    "La matrícula ingresada ya existe en el sistema.",
                    "Matrícula duplicada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Crear camión ────────────────────────────────────────────────────
        Camion c = new Camion();
        c.setAnio(anio);
        c.setMarca(txt_marca.getText());
        c.setModelo((String) cmb_modelo.getSelectedItem());
        c.setMatricula(matriculaNormalizada);   // guardamos normalizada

        Personal seleccionado = (Personal) cmb_conductor.getSelectedItem();
        c.setConductor(seleccionado);

        if (c.getKilometrajeTotal() == null) {
            c.setKilometrajeTotal(0);
        }

        dp.create(c);

        JOptionPane.showMessageDialog(this, "Camión registrado correctamente.");
        cargarTabla();
        cargarComboConductores();
        limpiarFormulario();
    }//GEN-LAST:event_bt_guardarActionPerformed
    /**
     * Maneja el evento de clic sobre una fila de la tabla de camiones. Obtiene
     * el ID del camión seleccionado y rellena automáticamente los campos del
     * formulario con los datos correspondientes (modelo, marca, año, conductor
     * y matrícula).
     *
     * @param evt Evento de ratón generado al hacer clic en la tabla
     * tbl_camiones.
     */
    private void tbl_camionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_camionesMouseClicked
        int selectedRow = this.tbl_camiones.getSelectedRow();

        if (selectedRow != -1) {

            Object cellValue = this.tbl_camiones.getValueAt(selectedRow, 0);

            Integer id_seleccionado = (Integer) cellValue;
            this.txt_id_camion.setText(id_seleccionado.toString());

            for (Camion c : dp.listarTodos()) {
                if (c.getIdCamion() == id_seleccionado) {
                    this.cmb_modelo.setSelectedItem(c.getModelo());
                    this.txt_marca.setText(c.getMarca());
                    this.txt_anio.setText(c.getAnio().toString());
                    this.cmb_conductor.setSelectedItem(c.getConductor());
                    this.txt_matricula.setText(c.getMatricula());
                }
            }

            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_camionesMouseClicked
    /**
     * Maneja el evento del botón "Guardar Cambios". Actualiza los datos del
     * camión seleccionado en la base de datos.
     * <p>
     * Realiza las siguientes operaciones:
     * <ul>
     * <li>Busca el camión por su ID usando
     * {@link DAOCamion#buscarPorId(Integer)}.</li>
     * <li>Verifica que la matrícula nueva no esté duplicada en el sistema.</li>
     * <li>Actualiza todos los campos del camión y persiste los cambios con
     * {@link DAOCamion#update(Camion)}.</li>
     * <li>Recarga la tabla y el combo de conductores.</li>
     * <li>Limpia el formulario tras la actualización exitosa.</li>
     * </ul>
     *
     * @param evt Evento de acción generado por el botón bt_guardar_cambios.
     */
    private void bt_guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardar_cambiosActionPerformed
        String matriculaRaw = txt_matricula.getText().trim();
        Integer id_seleccionado = Integer.parseInt(txt_id_camion.getText());

        Camion c = dp.buscarPorId(id_seleccionado);
        if (c == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró el camión a modificar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ── Validación año ──────────────────────────────────────────────────
        int anio;
        try {
            anio = Integer.parseInt(txt_anio.getText().trim());
            if (anio <= 0) {
                JOptionPane.showMessageDialog(this,
                        "El año debe ser un número positivo.",
                        "Año inválido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "El año ingresado no es válido. Ingrese solo números.",
                    "Año inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Validación formato matrícula ────────────────────────────────────
        if (!validarFormatoMatricula(matriculaRaw)) {
            JOptionPane.showMessageDialog(this,
                    "Formato de matrícula inválido.\n"
                    + "Use el formato antiguo (AB1234) o nuevo (ABCD12).\n"
                    + "El guion es opcional.",
                    "Matrícula inválida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String matriculaNormalizada = normalizarMatricula(matriculaRaw);

        // ── Validación duplicado (excluye el camión actual) ─────────────────
        if (dp.existeMatricula(matriculaNormalizada, id_seleccionado)) {
            JOptionPane.showMessageDialog(this,
                    "La matrícula ingresada ya pertenece a otro camión.",
                    "Matrícula duplicada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ── Aplicar cambios ─────────────────────────────────────────────────
        c.setMarca(txt_marca.getText());
        c.setModelo((String) cmb_modelo.getSelectedItem());
        c.setAnio(anio);
        c.setMatricula(matriculaNormalizada);   // guardamos normalizada

        Personal seleccionado = (Personal) cmb_conductor.getSelectedItem();
        c.setConductor(seleccionado);

        dp.update(c);

        JOptionPane.showMessageDialog(this, "Camión modificado correctamente.");
        cargarTabla();
        cargarComboConductores();
        activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_guardar_cambiosActionPerformed
    /**
     * Maneja el evento del botón "Eliminar". Busca el camión cuyo ID coincide
     * con el ingresado en {@code txt_id_camion} y lo elimina de la base de
     * datos mediante {@link DAOCamion#delete(Integer)}. Luego recarga la tabla
     * y limpia el formulario.
     *
     * @param evt Evento de acción generado por el botón bt_eliminar.
     */
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        Integer id_seleccionado = Integer.parseInt(this.txt_id_camion.getText());
        Camion c_encontrado = new Camion();
        for (Camion c : dp.listarTodos()) {
            if (c.getIdCamion() == id_seleccionado) {
                c_encontrado = c;
            }
        }
        dp.delete(c_encontrado.getIdCamion());
        this.activarModoNuevo();
        cargarTabla();
        limpiarFormulario();


    }//GEN-LAST:event_bt_eliminarActionPerformed
    /**
     * Carga y actualiza la tabla {@code tbl_camiones} con todos los camiones
     * registrados en la base de datos.
     * <p>
     * Las columnas mostradas son: ID, Conductor, Año, Marca, Modelo y
     * Matrícula. Crea un nuevo {@link DefaultTableModel} en cada llamada para
     * reflejar los datos más recientes.
     */

    public void cargarTabla() {

        // 1. Define los encabezados de la tabla
        Object[] nombresColumnas = {"ID", "Conductór", "Año", "Marca", "Modelo", "Matricula"};

        // 2. Crea el modelo de tabla
        DefaultTableModel modelo = new DefaultTableModel(nombresColumnas, 0);

        // 3. Carga datos desde el ArrayList
        for (Camion c : dp.listarTodos()) {
            Object[] row1 = {c.getIdCamion(), c.getConductor(), c.getAnio(), c.getMarca(), c.getModelo(), c.getMatricula()};
            modelo.addRow(row1);
        }

        // 4. Establece el modelo actual a la tabla
        this.tbl_camiones.setModel(modelo);
    }

    /**
     * Activa el modo edición en el formulario, habilitando los botones de
     * cancelar, guardar cambios y eliminar, y deshabilitando el botón de
     * registrar. Se usa cuando hay un conductor seleccionado en la tabla.
     */
    private void activarModoEditar() {
        this.bt_cancelar.setEnabled(true);
        this.bt_guardar_cambios.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_guardar.setEnabled(false);
    }

    /**
     * Activa el modo nuevo para ingresar un cliente.
     */
    private void activarModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_guardar_cambios.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_guardar.setEnabled(true);
    }
    /**
     * Objeto de acceso a datos para operaciones CRUD sobre {@link Camion}.
     */
    DAOCamion dp = new DAOCamion();

    /**
     * Objeto de acceso a datos para consultas sobre {@link Personal}.
     */
    private DAOPersonal daoPersonal = new DAOPersonal();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar;
    private javax.swing.JButton bt_guardar_cambios;
    private javax.swing.JComboBox<Personal> cmb_conductor;
    private javax.swing.JComboBox<String> cmb_modelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_camiones;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_id_camion;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_matricula;
    // End of variables declaration//GEN-END:variables
}
