/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;
import com.mycompany.transporte_mercancia.Data.DAOMantenimientoEquipo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author saave
 */
public class FrmConsultaMantenimientoEquipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultaMantenimientoEquipos
     */
    public FrmConsultaMantenimientoEquipos() {
        initComponents();
        initConsulta();
    }
      private void initConsulta() {
        configurarTabla();
        cargarDatos(null, "Todos", null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_historial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_num_serie = new javax.swing.JTextField();
        cmb_tipo_mant = new javax.swing.JComboBox<>();
        jdc_fecha_desde = new com.toedter.calendar.JDateChooser();
        jdc_fecha_hasta = new com.toedter.calendar.JDateChooser();
        bt_buscar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();

        tbl_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_historial);

        jLabel1.setText("Buscar mantenimientos de equipos:");

        cmb_tipo_mant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Preventivo", "Correctivo" }));

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });

        lbl_total.setText("Total registros: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_total)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cmb_tipo_mant, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdc_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jdc_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_num_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_buscar)
                            .addComponent(bt_limpiar))
                        .addGap(214, 214, 214))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipo_mant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_num_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_buscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdc_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jdc_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lbl_total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Lee los valores de los filtros y ejecuta la consulta.
     * Conectar en NetBeans: clic derecho bt_buscar → Events → Action → actionPerformed.
     */
    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
       // Número de serie (vacío = sin filtro)
        String numSerie = txt_num_serie.getText().trim();
        if (numSerie.isEmpty()) numSerie = null;

        // Tipo de mantenimiento
        String tipo = (String) cmb_tipo_mant.getSelectedItem();

        // Fechas
        java.sql.Date fechaDesde = null;
        java.sql.Date fechaHasta = null;

        if (jdc_fecha_desde.getDate() != null) {
            fechaDesde = new java.sql.Date(jdc_fecha_desde.getDate().getTime());
        }
        if (jdc_fecha_hasta.getDate() != null) {
            fechaHasta = new java.sql.Date(jdc_fecha_hasta.getDate().getTime());
        }

        // Validar rango de fechas
        if (fechaDesde != null && fechaHasta != null && fechaDesde.after(fechaHasta)) {
            JOptionPane.showMessageDialog(
                this,
                "La fecha 'Desde' no puede ser posterior a la fecha 'Hasta'.",
                "Rango de fechas inválido",
                JOptionPane.WARNING_MESSAGE
            );
            jdc_fecha_desde.requestFocus();
            return;
        }

        cargarDatos(numSerie, tipo, fechaDesde, fechaHasta);
    }//GEN-LAST:event_bt_buscarActionPerformed
/**
     * Restablece todos los filtros y recarga el historial completo.
     * Conectar en NetBeans: clic derecho bt_limpiar → Events → Action → actionPerformed.
     */
    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
       txt_num_serie.setText("");
        cmb_tipo_mant.setSelectedIndex(0); // "Todos"
        jdc_fecha_desde.setDate(null);
        jdc_fecha_hasta.setDate(null);
        cargarDatos(null, "Todos", null, null);
        txt_num_serie.requestFocus();
    }//GEN-LAST:event_bt_limpiarActionPerformed
 
    private void configurarTabla() {
        String[] columnas = {
            "ID",               // 0 — oculto
            "N° Serie",         // 1
            "Marca",            // 2
            "Tipo Equipo",      // 3
            "Tipo Mant.",       // 4
            "Fecha Entrada",    // 5
            "Fecha Salida",     // 6
            "Descripción"       // 7
        };

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false; // tabla de solo lectura
            }
        };

        tbl_historial.setModel(modelo);
        tbl_historial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_historial.setAutoCreateRowSorter(true); // permite ordenar columnas con clic

        // Ocultar columna ID
        tbl_historial.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_historial.getColumnModel().getColumn(0).setMaxWidth(0);
        tbl_historial.getColumnModel().getColumn(0).setWidth(0);

        // Ajustar anchos sugeridos
        tbl_historial.getColumnModel().getColumn(1).setPreferredWidth(110); // N° Serie
        tbl_historial.getColumnModel().getColumn(2).setPreferredWidth(100); // Marca
        tbl_historial.getColumnModel().getColumn(3).setPreferredWidth(80);  // Tipo Equipo
        tbl_historial.getColumnModel().getColumn(4).setPreferredWidth(90);  // Tipo Mant.
        tbl_historial.getColumnModel().getColumn(5).setPreferredWidth(90);  // Fecha Entrada
        tbl_historial.getColumnModel().getColumn(6).setPreferredWidth(90);  // Fecha Salida
        tbl_historial.getColumnModel().getColumn(7).setPreferredWidth(200); // Descripción
    }
    
     /**
     * Consulta el historial aplicando los filtros recibidos y puebla la tabla.
     *
     * @param numeroSerie       parcial o null para sin filtro.
     * @param tipoMantenimiento "Todos", "Preventivo" o "Correctivo".
     * @param fechaDesde        fecha mínima de entrada; null para ignorar.
     * @param fechaHasta        fecha máxima de entrada; null para ignorar.
     */
    private void cargarDatos(String numeroSerie,
                              String tipoMantenimiento,
                              java.sql.Date fechaDesde,
                              java.sql.Date fechaHasta) {

        DefaultTableModel modelo = (DefaultTableModel) tbl_historial.getModel();
        modelo.setRowCount(0); // limpiar filas anteriores

        ArrayList<Object[]> lista = dao.listarHistorialFiltrado(
                numeroSerie, tipoMantenimiento, fechaDesde, fechaHasta);

        if (lista.isEmpty()) {
            lbl_total.setText("No se encontraron registros.");
            return;
        }

        for (Object[] fila : lista) {
            // Formatear fechas para mostrar en la tabla
            String fechaEntrada = (fila[5] != null) ? SDF.format(fila[5]) : "—";
            String fechaSalida  = (fila[6] != null) ? SDF.format(fila[6]) : "—";

            modelo.addRow(new Object[]{
                fila[0],        // ID (oculto)
                fila[1],        // N° Serie
                fila[2],        // Marca
                fila[3],        // Tipo Equipo
                fila[4],        // Tipo Mant.
                fechaEntrada,   // Fecha Entrada formateada
                fechaSalida,    // Fecha Salida formateada
                fila[7]         // Descripción
            });
        }

        lbl_total.setText("Total registros: " + lista.size());
    }
    
    
    
    
    
    
private final SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy"); 
private final DAOMantenimientoEquipo dao = new DAOMantenimientoEquipo();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JComboBox<String> cmb_tipo_mant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_fecha_desde;
    private com.toedter.calendar.JDateChooser jdc_fecha_hasta;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tbl_historial;
    private javax.swing.JTextField txt_num_serie;
    // End of variables declaration//GEN-END:variables
}

