/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Logica.Personal;
import com.mycompany.transporte_mercancia.Data.DAOPersonal;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmConductores extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConductores
     */
    public FrmConductores() {
        initComponents();
        cargarTabla();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_conductores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_guardar_cambios = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_id_conductor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_rut = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JTextField();
        bt_cerrar_pestaña = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();

        tbl_conductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_conductores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_conductoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_conductores);

        jLabel1.setText("Nombre");

        bt_registrar.setText("Registrar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_guardar_cambios.setText("Guardar cambios");
        bt_guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guardar_cambiosActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        txt_id_conductor.setEditable(false);

        jLabel5.setText("Rut");

        jLabel6.setText("Contraseña");

        txt_contrasena.setText(" ");

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_actualizar_pestaña)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cerrar_pestaña))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_nombre)
                                        .addComponent(txt_id_conductor, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(txt_rut)))
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_guardar_cambios)
                                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cerrar_pestaña)
                            .addComponent(bt_actualizar_pestaña))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_id_conductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar)
                            .addComponent(bt_guardar_cambios))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar))))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Maneja el evento de clic sobre una fila de la tabla de conductores.
     * Recupera el ID del conductor seleccionado, rellena los campos del
     * formulario con sus datos (RUT, nombre y contraseña) y activa el modo
     * edición.
     *
     * @param evt Evento de ratón generado al hacer clic en la tabla
     * tbl_conductores.
     */
    private void tbl_conductoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_conductoresMouseClicked
        int selectedRow = this.tbl_conductores.getSelectedRow();
        if (selectedRow != -1) {
            Integer id_seleccionado = (Integer) this.tbl_conductores.getValueAt(selectedRow, 0);
            this.txt_id_conductor.setText(id_seleccionado.toString());

            for (Personal p : dp.listarPorRol("conductor")) {
                if (p.getIdPersonal() == id_seleccionado) {
                    this.txt_rut.setText(p.getRut());
                    this.txt_nombre.setText(p.getNombre());
                    this.txt_contrasena.setText(p.getContrasena());

                }
            }
            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_conductoresMouseClicked
    /**
     * Maneja el evento del botón "Registrar". Valida el RUT ingresado (formato
     * y dígito verificador) y verifica que no exista previamente en el sistema
     * antes de crear un nuevo conductor.
     * <p>
     * El rol asignado automáticamente es {@code "conductor"}. Tras el registro
     * exitoso recarga la tabla y limpia el formulario.
     *
     * @param evt Evento de acción generado por el botón bt_registrar.
     */
    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        String rutIngresado = txt_rut.getText().trim();

        if (!validarRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this, "El RUT ingresado no es válido.\nEjemplo: 12.345.678-5",
                    "Rut inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (dp.existeRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this, "El RUT ingresado ya existe en el sistema.",
                    "RUT duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Personal p = new Personal();
        p.setRut(this.txt_rut.getText().trim());
        p.setNombre(this.txt_nombre.getText().trim());
        p.setContrasena(this.txt_contrasena.getText().trim());
        p.setRol("conductor");

        dp.create(p);

        JOptionPane.showMessageDialog(this, "Conductor registrado correctamente.");
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_bt_registrarActionPerformed
    /**
     * Maneja el evento del botón "Guardar Cambios". Actualiza los datos del
     * conductor seleccionado en la base de datos.
     * <p>
     * Busca el conductor por ID entre los de rol "conductor", verifica que el
     * nuevo RUT no esté duplicado y persiste los cambios con
     * {@link DAOPersonal#update(Personal)}. Luego recarga la tabla, activa el
     * modo nuevo y limpia el formulario.
     *
     * @param evt Evento de acción generado por el botón bt_guardar_cambios.
     */
    private void bt_guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guardar_cambiosActionPerformed
        String rutIngresado = txt_rut.getText().trim();
        Integer id_seleccionado = Integer.parseInt(this.txt_id_conductor.getText());

        // 1. Validar formato del RUT
        if (!validarRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this, "El RUT ingresado no es válido.\nEjemplo: 12.345.678-5",
                    "Rut inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Verificar duplicado excluyendo al propio conductor
        if (dp.existeRut(rutIngresado, id_seleccionado)) {
            JOptionPane.showMessageDialog(this, "El RUT ingresado ya existe en el sistema.",
                    "RUT duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Buscar el Personal y actualizar
        Personal p = null;
        for (Personal busqueda : dp.listarPorRol("conductor")) {
            if (busqueda.getIdPersonal() == id_seleccionado) {
                p = busqueda;
                break;
            }
        }

        if (p != null) {
            p.setRut(rutIngresado);
            p.setNombre(this.txt_nombre.getText().trim());
            p.setContrasena(this.txt_contrasena.getText().trim());
            p.setRol("conductor");

            dp.update(p);

            JOptionPane.showMessageDialog(this, "Conductor actualizado correctamente.");
            cargarTabla();
            activarModoNuevo();
            limpiarFormulario();
        }
    }//GEN-LAST:event_bt_guardar_cambiosActionPerformed
    /**
     * Maneja el evento del botón "Eliminar". Elimina el conductor cuyo ID está
     * indicado en {@code txt_id_conductor} mediante
     * {@link DAOPersonal#delete(Integer)}. Luego recarga la tabla y limpia el
     * formulario.
     *
     * @param evt Evento de acción generado por el botón bt_eliminar.
     */
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        Integer id_seleccionado = Integer.parseInt(this.txt_id_conductor.getText());
        dp.delete(id_seleccionado);
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_bt_eliminarActionPerformed
    /**
     * Maneja el evento del botón "Cancelar". Activa el modo nuevo y limpia
     * todos los campos del formulario.
     *
     * @param evt Evento de acción generado por el botón bt_cancelar.
     */
    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_cancelarActionPerformed
    /**
     * Limpia todos los campos de entrada del formulario de conductores,
     * restableciendo RUT, nombre, contraseña e ID a cadena vacía.
     */
    private void limpiarFormulario() {
        this.txt_rut.setText("");
        this.txt_nombre.setText("");
        this.txt_contrasena.setText("");
        this.txt_id_conductor.setText("");

    }

    /**
     * Formatea un RUT eliminando puntos y guión, y lo devuelve en el formato
     * {@code NNNNNNNN-D} (número seguido de guión y dígito verificador en
     * mayúscula).
     *
     * @param rut RUT en cualquier formato de entrada.
     * @return RUT formateado como {@code "12345678-5"} o {@code "12345678-K"}.
     */
    public String formatearRut(String rut) {
        rut = rut.replace(".", "").replace("-", "").toUpperCase();
        String numero = rut.substring(0, rut.length() - 1);
        String dv = rut.substring(rut.length() - 1);
        return numero + "-" + dv;
    }

    /**
     * Verifica que el RUT tenga el formato básico {@code NNNNNNNN-D}, es decir,
     * dígitos seguidos de un guión y un dígito o la letra K.
     *
     * @param rut RUT a validar (sin puntos, con guión).
     * @return {@code true} si el formato es correcto; {@code false} en caso
     * contrario.
     */
    public boolean validarFormato(String rut) {
        return rut.matches("^[0-9]+-[0-9K]$");
    }

    /**
     * Valida el RUT completo verificando el dígito verificador.
     *
     * @param rut RUT ingresado
     * @return true si el RUT es válido
     */
    public boolean validarRut(String rut) {
        if (rut == null || rut.trim().isEmpty()) {
            return false;
        }

        rut = rut.replace(".", "").replace("-", "").toUpperCase();

        if (!rut.matches("^\\d{7,8}[0-9K]$")) {
            return false;
        }

        String numero = rut.substring(0, rut.length() - 1);  // todo menos DV
        String dvIngresado = rut.substring(rut.length() - 1);

        String dvCalculado = calcularDV(numero);

        return dvIngresado.equals(dvCalculado);
    }

    /**
     * Calcula el dígito verificador (DV) del RUT.
     *
     * @param rut número del RUT sin DV
     * @return dígito verificador calculado
     */
    // Cálculo tradicional del DV
    public String calcularDV(String rut) {
        int suma = 0;
        int multiplicador = 2;

        for (int i = rut.length() - 1; i >= 0; i--) {
            suma += Character.getNumericValue(rut.charAt(i)) * multiplicador;
            multiplicador = (multiplicador == 7) ? 2 : multiplicador + 1;
        }

        int residuo = 11 - (suma % 11);

        if (residuo == 11) {
            return "0";
        }
        if (residuo == 10) {
            return "K";
        }
        return String.valueOf(residuo);
    }

    /**
     * Carga y actualiza la tabla {@code tbl_conductores} con todos los
     * conductores registrados en la base de datos (filtrados por rol
     * "conductor").
     * <p>
     * Las columnas mostradas son: ID, RUT y Nombre.
     */
    public void cargarTabla() {

        Object[] nombresColumnas = {"ID", "RUT", "Nombre"};
        DefaultTableModel modelo = new DefaultTableModel(nombresColumnas, 0);

        for (Personal p : dp.listarPorRol("conductor")) {
            Object[] row = {p.getIdPersonal(), p.getRut(), p.getNombre()};
            modelo.addRow(row);
        }

        this.tbl_conductores.setModel(modelo);
    }

    /**
     * Activa el modo edición en el formulario, habilitando los botones de
     * cancelar, guardar cambios y eliminar, y deshabilitando el botón de
     * registrar. Se usa cuando hay un conductor seleccionado en la tabla.
     */
    private void activarModoEditar() {
        this.bt_cancelar.setEnabled(true);
        this.bt_guardar_cambios.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_registrar.setEnabled(false);
    }

    /**
     * Activa el modo nuevo para ingresar un cliente.
     */
    private void activarModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_guardar_cambios.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_registrar.setEnabled(true);
    }

    /**
     * Objeto de acceso a datos para operaciones CRUD sobre {@link Personal}.
     */
    DAOPersonal dp = new DAOPersonal();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_guardar_cambios;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_conductores;
    private javax.swing.JTextField txt_contrasena;
    private javax.swing.JTextField txt_id_conductor;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
