/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAODetallePiezaMantenimiento;
import com.mycompany.transporte_mercancia.Data.DAOMantenimientoEquipo;
import com.mycompany.transporte_mercancia.Logica.DetallePiezaMantenimiento;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

public class FrmConsultaMantenimientoEquipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmConsultaMantenimientoEquipos
     */
    public FrmConsultaMantenimientoEquipos() {
        initComponents();
        aplicarEstilos();
        initConsulta();
    }

    private void initConsulta() {
        configurarTabla();
        cargarDatos(null, "Todos", null, null);
        configurarSeleccionTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_historial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_num_serie = new javax.swing.JTextField();
        cmb_tipo_mant = new javax.swing.JComboBox<>();
        jdc_fecha_desde = new com.toedter.calendar.JDateChooser();
        jdc_fecha_hasta = new com.toedter.calendar.JDateChooser();
        bt_buscar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        bt_ver_detalles = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        tbl_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_historial);

        jLabel1.setText("Buscar mantenimientos de equipos:");

        cmb_tipo_mant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Preventivo", "Correctivo" }));

        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limpiarActionPerformed(evt);
            }
        });

        lbl_total.setText("Total registros: 0");

        bt_ver_detalles.setText("Detalles");
        bt_ver_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ver_detallesActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Desde:");

        jLabel3.setText("Hasta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_tipo_mant, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdc_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdc_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_num_serie))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(bt_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(188, 188, 188))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_total)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_ver_detalles))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipo_mant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_num_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_buscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_limpiar)
                                .addGap(0, 5, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdc_fecha_desde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jdc_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_total)
                    .addComponent(bt_ver_detalles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Lee los valores de los filtros y ejecuta la consulta. Conectar en
     * NetBeans: clic derecho bt_buscar → Events → Action → actionPerformed.
     */

    private void configurarSeleccionTabla() {
        tbl_historial.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                boolean haySeleccion = tbl_historial.getSelectedRow() != -1;
                bt_ver_detalles.setEnabled(haySeleccion);
            }
        });
    }
    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        // Número de serie (vacío = sin filtro)
        String numSerie = txt_num_serie.getText().trim();
        if (numSerie.isEmpty()) {
            numSerie = null;
        }

        // Tipo de mantenimiento
        String tipo = (String) cmb_tipo_mant.getSelectedItem();

        // Fechas
        java.sql.Date fechaDesde = null;
        java.sql.Date fechaHasta = null;

        if (jdc_fecha_desde.getDate() != null) {
            fechaDesde = new java.sql.Date(jdc_fecha_desde.getDate().getTime());
        }
        if (jdc_fecha_hasta.getDate() != null) {
            fechaHasta = new java.sql.Date(jdc_fecha_hasta.getDate().getTime());
        }

        // Validar rango de fechas
        if (fechaDesde != null && fechaHasta != null && fechaDesde.after(fechaHasta)) {
            JOptionPane.showMessageDialog(
                    this,
                    "La fecha 'Desde' no puede ser posterior a la fecha 'Hasta'.",
                    "Rango de fechas inválido",
                    JOptionPane.WARNING_MESSAGE
            );
            jdc_fecha_desde.requestFocus();
            return;
        }

        cargarDatos(numSerie, tipo, fechaDesde, fechaHasta);
    }//GEN-LAST:event_bt_buscarActionPerformed
    /**
     * Restablece todos los filtros y recarga el historial completo. Conectar en
     * NetBeans: clic derecho bt_limpiar → Events → Action → actionPerformed.
     */
    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        txt_num_serie.setText("");
        cmb_tipo_mant.setSelectedIndex(0); // "Todos"
        jdc_fecha_desde.setDate(null);
        jdc_fecha_hasta.setDate(null);
        cargarDatos(null, "Todos", null, null);
        txt_num_serie.requestFocus();
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void bt_ver_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ver_detallesActionPerformed
        int filaVista = tbl_historial.getSelectedRow();
        if (filaVista == -1) {
            return;
        }

        // Convertir fila visible → fila del modelo (por si hay ordenamiento activo)
        int filaModelo = tbl_historial.convertRowIndexToModel(filaVista);
        DefaultTableModel modelo = (DefaultTableModel) tbl_historial.getModel();

        int idMantenimiento = (int) modelo.getValueAt(filaModelo, 0); // columna ID oculta
        mostrarDialogDetalles(idMantenimiento, modelo, filaModelo);
    }//GEN-LAST:event_bt_ver_detallesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void configurarTabla() {
        String[] columnas = {
            "ID", // 0 — oculto
            "N° Serie", // 1
            "Marca", // 2
            "Tipo Equipo", // 3
            "Tipo Mant.", // 4
            "Estado", // 5  ← nuevo
            "Fecha Entrada", // 6
            "Fecha Fin", // 7  ← era "Fecha Salida"
            "Días Activos", // 8  ← nuevo
            "Descripción" // 9
        };

        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        tbl_historial.setModel(modelo);
        tbl_historial.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_historial.setAutoCreateRowSorter(true);

        // Ocultar columna ID
        tbl_historial.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_historial.getColumnModel().getColumn(0).setMaxWidth(0);
        tbl_historial.getColumnModel().getColumn(0).setWidth(0);

        // Anchos
        tbl_historial.getColumnModel().getColumn(1).setPreferredWidth(110); // N° Serie
        tbl_historial.getColumnModel().getColumn(2).setPreferredWidth(100); // Marca
        tbl_historial.getColumnModel().getColumn(3).setPreferredWidth(80);  // Tipo Equipo
        tbl_historial.getColumnModel().getColumn(4).setPreferredWidth(90);  // Tipo Mant.
        tbl_historial.getColumnModel().getColumn(5).setPreferredWidth(90);  // Estado
        tbl_historial.getColumnModel().getColumn(6).setPreferredWidth(90);  // Fecha Entrada
        tbl_historial.getColumnModel().getColumn(7).setPreferredWidth(90);  // Fecha Fin
        tbl_historial.getColumnModel().getColumn(8).setPreferredWidth(70);  // Días Activos
        tbl_historial.getColumnModel().getColumn(9).setPreferredWidth(200); // Descripción
    }

    private void mostrarDialogDetalles(int idMantenimiento,
            DefaultTableModel modelo,
            int filaModelo) {

        // ── Obtener datos del mantenimiento desde la tabla ────────
        String numSerie = String.valueOf(modelo.getValueAt(filaModelo, 1));
        String marca = String.valueOf(modelo.getValueAt(filaModelo, 2));
        String tipoEquipo = String.valueOf(modelo.getValueAt(filaModelo, 3));
        String tipoMant = String.valueOf(modelo.getValueAt(filaModelo, 4));
        String estado = String.valueOf(modelo.getValueAt(filaModelo, 5));
        String fechaEntrada = String.valueOf(modelo.getValueAt(filaModelo, 6));
        String fechaFin = String.valueOf(modelo.getValueAt(filaModelo, 7));
        Object diasObj = modelo.getValueAt(filaModelo, 8);
        String diasActivos = (diasObj != null) ? String.valueOf(diasObj) : "—";
        String descripcion = String.valueOf(modelo.getValueAt(filaModelo, 9));

        // ── Crear diálogo modal ───────────────────────────────────
        JDialog dialog = new JDialog(
                SwingUtilities.getWindowAncestor(this),
                "Detalles del Mantenimiento — ID " + idMantenimiento,
                Dialog.ModalityType.APPLICATION_MODAL
        );
        dialog.setSize(620, 500);
        dialog.setLocationRelativeTo(this);
        dialog.setLayout(new BorderLayout(0, 0));
        dialog.setResizable(false);

        // ── Panel superior: datos generales del mantenimiento ─────
        JPanel pnlInfo = new JPanel(new GridBagLayout());
        pnlInfo.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder(
                        BorderFactory.createEtchedBorder(),
                        "Información del Mantenimiento",
                        javax.swing.border.TitledBorder.LEFT,
                        javax.swing.border.TitledBorder.TOP,
                        new Font("SansSerif", Font.BOLD, 12)
                ),
                BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(3, 6, 3, 6);

        // Fila 0
        agregarFilaInfo(pnlInfo, gbc, 0, "N° Serie:", numSerie,
                "Marca:", marca);
        // Fila 1
        agregarFilaInfo(pnlInfo, gbc, 1, "Tipo Equipo:", tipoEquipo,
                "Tipo Mant.:", tipoMant);
        // Fila 2
        agregarFilaInfo(pnlInfo, gbc, 2, "Estado:", estado,
                "Días Activos:", diasActivos);
        // Fila 3
        agregarFilaInfo(pnlInfo, gbc, 3, "Fecha Entrada:", fechaEntrada,
                "Fecha Fin:", fechaFin);
        // Fila 4 — descripción ocupa todo el ancho
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 0;
        pnlInfo.add(new JLabel("Descripción:"), gbc);
        gbc.gridx = 1;
        gbc.gridwidth = 3;
        gbc.weightx = 1;
        JLabel lblDesc = new JLabel(
                descripcion.equals("null") || descripcion.isBlank() ? "—" : descripcion
        );
        pnlInfo.add(lblDesc, gbc);
        gbc.gridwidth = 1;

        // ── Panel central: tabla de piezas ────────────────────────
        JPanel pnlPiezas = new JPanel(new BorderLayout());
        pnlPiezas.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder(
                        BorderFactory.createEtchedBorder(),
                        "Piezas utilizadas en este mantenimiento",
                        javax.swing.border.TitledBorder.LEFT,
                        javax.swing.border.TitledBorder.TOP,
                        new Font("SansSerif", Font.BOLD, 12)
                ),
                BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));

        String[] columnasPiezas = {"#", "Nombre de la Pieza", "Cantidad"};
        DefaultTableModel modeloPiezas = new DefaultTableModel(columnasPiezas, 0) {
            @Override
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };

        JTable tblPiezas = new JTable(modeloPiezas);
        tblPiezas.setFillsViewportHeight(true);
        tblPiezas.setRowHeight(22);
        tblPiezas.getTableHeader().setReorderingAllowed(false);
        tblPiezas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPiezas.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblPiezas.getColumnModel().getColumn(1).setPreferredWidth(320);
        tblPiezas.getColumnModel().getColumn(2).setPreferredWidth(80);

        // Cargar piezas desde la BD
        DAODetallePiezaMantenimiento daoDetalle = new DAODetallePiezaMantenimiento();
        ArrayList<DetallePiezaMantenimiento> detalles
                = daoDetalle.listarPorMantenimiento(idMantenimiento);

        if (detalles.isEmpty()) {
            modeloPiezas.addRow(new Object[]{"—", "Sin piezas registradas", "—"});
        } else {
            int n = 1;
            for (DetallePiezaMantenimiento d : detalles) {
                modeloPiezas.addRow(new Object[]{
                    n++,
                    d.getNombrePieza(),
                    d.getCantidad()
                });
            }
        }

        // Etiqueta de total de piezas
        int totalPiezas = detalles.size();
        JLabel lblTotalPiezas = new JLabel(
                totalPiezas > 0
                        ? "Total piezas distintas: " + totalPiezas
                        : "No se registraron piezas para este mantenimiento."
        );
        lblTotalPiezas.setBorder(BorderFactory.createEmptyBorder(4, 2, 0, 0));

        pnlPiezas.add(new JScrollPane(tblPiezas), BorderLayout.CENTER);
        pnlPiezas.add(lblTotalPiezas, BorderLayout.SOUTH);

        // ── Panel inferior: botón Cerrar ─────────────────────────
        JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnCerrar = new JButton("Cerrar");
        btnCerrar.addActionListener(e -> dialog.dispose());
        pnlBotones.add(btnCerrar);

        // ── Ensamblar diálogo ─────────────────────────────────────
        dialog.add(pnlInfo, BorderLayout.NORTH);
        dialog.add(pnlPiezas, BorderLayout.CENTER);
        dialog.add(pnlBotones, BorderLayout.SOUTH);

        dialog.setVisible(true);
    }

    private void cargarDatos(String numeroSerie,
            String tipoMantenimiento,
            java.sql.Date fechaDesde,
            java.sql.Date fechaHasta) {

        DefaultTableModel modelo = (DefaultTableModel) tbl_historial.getModel();
        modelo.setRowCount(0);

        ArrayList<Object[]> lista = dao.listarHistorialFiltrado(
                numeroSerie, tipoMantenimiento, fechaDesde, fechaHasta);

        if (lista.isEmpty()) {
            lbl_total.setText("No se encontraron registros.");
            return;
        }

        for (Object[] fila : lista) {
            String fechaEntrada = (fila[6] != null) ? SDF.format(fila[6]) : "—";
            String fechaFin = (fila[7] != null) ? SDF.format(fila[7]) : "—";

            modelo.addRow(new Object[]{
                fila[0], // ID (oculto)
                fila[1], // N° Serie
                fila[2], // Marca
                fila[3], // Tipo Equipo
                fila[4], // Tipo Mant.
                fila[5], // Estado
                fechaEntrada, // Fecha Entrada
                fechaFin, // Fecha Fin
                fila[8], // Días Activos
                fila[9] // Descripción
            });
        }

        lbl_total.setText("Total registros: " + lista.size());
    }

    private void agregarFilaInfo(JPanel panel, GridBagConstraints gbc, int fila,
            String lbl1, String val1,
            String lbl2, String val2) {
        Font fuenteNegrita = new Font("SansSerif", Font.BOLD, 12);

        gbc.gridx = 0;
        gbc.gridy = fila;
        gbc.weightx = 0;
        JLabel label1 = new JLabel(lbl1);
        label1.setFont(fuenteNegrita);
        panel.add(label1, gbc);

        gbc.gridx = 1;
        gbc.weightx = 0.4;
        panel.add(new JLabel(val1.equals("null") || val1.isBlank() ? "—" : val1), gbc);

        gbc.gridx = 2;
        gbc.weightx = 0;
        JLabel label2 = new JLabel(lbl2);
        label2.setFont(fuenteNegrita);
        panel.add(label2, gbc);

        gbc.gridx = 3;
        gbc.weightx = 0.4;
        panel.add(new JLabel(val2.equals("null") || val2.isBlank() ? "—" : val2), gbc);
    }

    private final SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy");
    private final DAOMantenimientoEquipo dao = new DAOMantenimientoEquipo();
    
    
    
    private void aplicarEstilos() {

        // ── Colores base ─────────────────────────────────────────────────────
        java.awt.Color BG_DARK   = new java.awt.Color(0x0A192F);
        java.awt.Color BG_MID    = new java.awt.Color(0x172A45);
        java.awt.Color BG_FIELD  = new java.awt.Color(0x1F3460);
        java.awt.Color MINT      = new java.awt.Color(0x64FFDA);
        java.awt.Color CYAN      = new java.awt.Color(0x57CBF2);
        java.awt.Color CORAL     = new java.awt.Color(0xFF6B6B);
        java.awt.Color GRAY_BTN  = new java.awt.Color(0x8892B0);
        java.awt.Color TEXT_MAIN = new java.awt.Color(0xCCD6F6);
        java.awt.Color ROW_ALT   = new java.awt.Color(0x112240);

        // ── Fuentes ──────────────────────────────────────────────────────────
        java.awt.Font FONT_LABEL = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
        java.awt.Font FONT_FIELD = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Font FONT_BTN   = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);

        // ── Panel principal ──────────────────────────────────────────────────
        getContentPane().setBackground(BG_DARK);

        // ── Título del InternalFrame ─────────────────────────────────────────
        setTitle("🔍  Consulta de Mantenimientos");
        setBackground(BG_MID);

        // ── Labels de filtro ─────────────────────────────────────────────────
        javax.swing.JLabel[] labels = { jLabel1, jLabel2, jLabel3 };
        for (javax.swing.JLabel lbl : labels) {
            if (lbl != null) {
                lbl.setForeground(TEXT_MAIN);
                lbl.setFont(FONT_LABEL);
            }
        }

        // ── Label de total de registros ──────────────────────────────────────
        if (lbl_total != null) {
            lbl_total.setForeground(MINT);
            lbl_total.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        }

        // ── Campo número de serie ─────────────────────────────────────────────
        if (txt_num_serie != null) {
            txt_num_serie.setBackground(BG_FIELD);
            txt_num_serie.setForeground(TEXT_MAIN);
            txt_num_serie.setCaretColor(MINT);
            txt_num_serie.setFont(FONT_FIELD);
            txt_num_serie.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(MINT, 1, true),
                javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
            ));
        }

        // ── ComboBox tipo mantenimiento ───────────────────────────────────────
        if (cmb_tipo_mant != null) {
            cmb_tipo_mant.setBackground(BG_FIELD);
            cmb_tipo_mant.setForeground(TEXT_MAIN);
            cmb_tipo_mant.setFont(FONT_FIELD);
            cmb_tipo_mant.setBorder(javax.swing.BorderFactory.createLineBorder(MINT, 1, true));
            cmb_tipo_mant.setRenderer(new javax.swing.DefaultListCellRenderer() {
                @Override
                public java.awt.Component getListCellRendererComponent(
                        javax.swing.JList<?> list, Object value, int index,
                        boolean isSelected, boolean cellHasFocus) {
                    super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                    setBackground(isSelected ? MINT : BG_FIELD);
                    setForeground(isSelected ? BG_DARK : TEXT_MAIN);
                    setFont(FONT_FIELD);
                    setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8));
                    return this;
                }
            });
        }

        // ── DateChoosers (fecha desde / hasta) ───────────────────────────────
        com.toedter.calendar.JDateChooser[] fechas = { jdc_fecha_desde, jdc_fecha_hasta };
        for (com.toedter.calendar.JDateChooser dc : fechas) {
            if (dc == null) continue;
            dc.setBackground(BG_DARK);
            dc.setForeground(TEXT_MAIN);
            dc.setFont(FONT_FIELD);
            dc.setBorder(javax.swing.BorderFactory.createLineBorder(MINT, 1, true));
            if (dc.getDateEditor() != null
                    && dc.getDateEditor().getUiComponent() instanceof javax.swing.JTextField) {
                javax.swing.JTextField tfDate =
                    (javax.swing.JTextField) dc.getDateEditor().getUiComponent();
                tfDate.setBackground(BG_FIELD);
                tfDate.setForeground(TEXT_MAIN);
                tfDate.setCaretColor(MINT);
                tfDate.setFont(FONT_FIELD);
            }
        }

        // ── Botones ───────────────────────────────────────────────────────────
        //   bt_buscar       → menta  (acción principal de búsqueda)
        //   bt_limpiar      → gris   (neutral / resetear filtros)
        //   bt_ver_detalles → celeste (acción secundaria)
        //   jButton1        → coral  (cerrar ventana)
        estilizarBoton(bt_buscar,       MINT,     BG_DARK, "O Buscar",       FONT_BTN);
        estilizarBoton(bt_limpiar,      GRAY_BTN, BG_DARK, "* Limpiar",       FONT_BTN);
        estilizarBoton(bt_ver_detalles, CYAN,     BG_DARK, "# Ver Detalles", FONT_BTN);
        estilizarBoton(jButton1,        CORAL,    BG_DARK, "X Cerrar",        FONT_BTN);

        // ── Tabla de historial ────────────────────────────────────────────────
        tbl_historial.setBackground(BG_MID);
        tbl_historial.setForeground(TEXT_MAIN);
        tbl_historial.setFont(FONT_FIELD);
        tbl_historial.setRowHeight(26);
        tbl_historial.setGridColor(new java.awt.Color(0x1F3460));
        tbl_historial.setSelectionBackground(MINT);
        tbl_historial.setSelectionForeground(BG_DARK);
        tbl_historial.setShowHorizontalLines(true);
        tbl_historial.setShowVerticalLines(false);

        // Cabecera de tabla
        javax.swing.table.JTableHeader header = tbl_historial.getTableHeader();
        header.setBackground(BG_MID);
        header.setForeground(MINT);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Renderer con filas alternas
        tbl_historial.setDefaultRenderer(Object.class,
            new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int column) {
                    super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    if (isSelected) {
                        setBackground(MINT);
                        setForeground(BG_DARK);
                    } else {
                        setBackground(row % 2 == 0 ? BG_MID : ROW_ALT);
                        setForeground(TEXT_MAIN);
                    }
                    setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
                    return this;
                }
            }
        );

        // ── ScrollPane ────────────────────────────────────────────────────────
        if (jScrollPane1 != null) {
            jScrollPane1.setBackground(BG_DARK);
            jScrollPane1.getViewport().setBackground(BG_MID);
            jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(0x1F3460), 1));
        }
    }

    /**
     * Aplica estilo visual uniforme a un JButton.
     * @param btn     Botón a estilizar
     * @param bg      Color de fondo
     * @param fg      Color de texto
     * @param texto   Texto/icono del botón
     * @param fuente  Fuente a usar
     */
    private void estilizarBoton(javax.swing.JButton btn,
                                java.awt.Color bg,
                                java.awt.Color fg,
                                String texto,
                                java.awt.Font fuente) {
        if (btn == null) return;
        btn.setText(texto);
        btn.setBackground(bg);
        btn.setForeground(fg);
        btn.setFont(fuente);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(bg.darker(), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(6, 14, 6, 14)
        ));
        // Efecto hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(bg.brighter());
            }
            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(bg);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JButton bt_ver_detalles;
    private javax.swing.JComboBox<String> cmb_tipo_mant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_fecha_desde;
    private com.toedter.calendar.JDateChooser jdc_fecha_hasta;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tbl_historial;
    private javax.swing.JTextField txt_num_serie;
    // End of variables declaration//GEN-END:variables
}
