/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOEquipoOficina;
import com.mycompany.transporte_mercancia.Logica.EquipoOficina;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmEquiposDeOficina extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmEquiposDeOficina
     */
    public FrmEquiposDeOficina() {
        initComponents();
        aplicarEstilos();
        cargarTabla();
        // Auto-mayúsculas mientras escribe
        txt_numero_serie.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                int pos = txt_numero_serie.getCaretPosition();
                String upper = txt_numero_serie.getText().toUpperCase();
                txt_numero_serie.setText(upper);
                txt_numero_serie.setCaretPosition(Math.min(pos, upper.length()));
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_equipos_oficina = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_equipo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_numero_serie = new javax.swing.JTextField();
        cmb_estado = new javax.swing.JComboBox<>();
        bt_registrar_equipo = new javax.swing.JButton();
        bt_modificar_equipo = new javax.swing.JButton();
        bt_eliminar_equipo = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bt_cerrar_pestaña = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();
        txt_tipo = new javax.swing.JTextField();

        tbl_equipos_oficina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_equipos_oficina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_equipos_oficinaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_equipos_oficina);

        jLabel1.setText("ID");

        jLabel2.setText("Tipo");

        jLabel3.setText("Marca");

        jLabel4.setText("Numero de serie");

        jLabel5.setText("Estado");

        txt_id_equipo.setEditable(false);

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativo", "En mantención", "Dado de baja" }));

        bt_registrar_equipo.setText("Registrar ");
        bt_registrar_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrar_equipoActionPerformed(evt);
            }
        });

        bt_modificar_equipo.setText("Modificar");
        bt_modificar_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificar_equipoActionPerformed(evt);
            }
        });

        bt_eliminar_equipo.setText("Eliminar");
        bt_eliminar_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminar_equipoActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        jLabel6.setText("PC-HP-001");

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 51));
        bt_cerrar_pestaña.setText("X");
        bt_cerrar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrar_pestañaActionPerformed(evt);
            }
        });

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");
        bt_actualizar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_pestañaActionPerformed(evt);
            }
        });

        txt_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_actualizar_pestaña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_cerrar_pestaña, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(bt_registrar_equipo)
                            .addComponent(bt_eliminar_equipo))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_modificar_equipo)
                            .addComponent(bt_cancelar)
                            .addComponent(txt_marca)
                            .addComponent(txt_numero_serie)
                            .addComponent(cmb_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cerrar_pestaña)
                            .addComponent(bt_actualizar_pestaña))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_numero_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar_equipo)
                            .addComponent(bt_modificar_equipo))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar_equipo)
                            .addComponent(bt_cancelar))))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Carga y actualiza la tabla {@code tbl_equipos_oficina} con todos los
     * equipos registrados en la base de datos.
     * <p>
     * Las columnas mostradas son: ID, Tipo, Marca, N° Serie y Estado.
     */
    public void cargarTabla() {
        Object[] nombresColumnas = {"ID", "Tipo", "Marca", "N° Serie", "Estado"};
        DefaultTableModel modelo = new DefaultTableModel(nombresColumnas, 0);

        for (EquipoOficina eq : daoEquipo.listarTodos()) {
            Object[] fila = {
                eq.getIdEquipo(),
                eq.getTipo(),
                eq.getMarca(),
                eq.getNumeroSerie(),
                eq.getEstado()
            };
            modelo.addRow(fila);
        }

        this.tbl_equipos_oficina.setModel(modelo);
    }

    /**
     * Limpia todos los campos de entrada del formulario de equipos,
     * restableciendo los textos a vacío y los combos a su primera opción.
     */
    private void limpiarFormulario() {
        this.txt_id_equipo.setText("");
        this.txt_marca.setText("");
        this.txt_numero_serie.setText("");
        this.txt_tipo.setText("");
        this.cmb_estado.setSelectedIndex(0);
    }

    /**
     * Maneja el evento de clic sobre una fila de la tabla de equipos. Obtiene
     * el ID del equipo seleccionado y rellena automáticamente los campos del
     * formulario con los datos correspondientes.
     *
     * @param evt Evento de ratón generado al hacer clic en la tabla.
     */
    private void tbl_equipos_oficinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_equipos_oficinaMouseClicked
        int selectedRow = this.tbl_equipos_oficina.getSelectedRow();

        if (selectedRow != -1) {
            Integer idSeleccionado = (Integer) this.tbl_equipos_oficina.getValueAt(selectedRow, 0);
            this.txt_id_equipo.setText(idSeleccionado.toString());

            EquipoOficina eq = daoEquipo.buscarPorId(idSeleccionado);
            if (eq != null) {
                this.txt_tipo.setText(eq.getTipo());
                this.txt_marca.setText(eq.getMarca());
                this.txt_numero_serie.setText(eq.getNumeroSerie());
                this.cmb_estado.setSelectedItem(eq.getEstado());
            }

            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_equipos_oficinaMouseClicked

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed
    /**
     * Maneja el evento del botón "Registrar". Registra un nuevo equipo de
     * oficina en el sistema con los datos ingresados en el formulario.
     * <p>
     * Realiza las siguientes validaciones y operaciones:
     * <ul>
     * <li>Verifica que los campos obligatorios no estén vacíos.</li>
     * <li>Verifica que el número de serie no exista previamente en la BD.</li>
     * <li>Persiste el equipo usando
     * {@link DAOEquipoOficina#create(EquipoOficina)}.</li>
     * <li>Recarga la tabla y limpia el formulario tras el registro
     * exitoso.</li>
     * </ul>
     *
     * @param evt Evento de acción generado por el botón bt_registrar_equipo.
     */
    private void bt_registrar_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrar_equipoActionPerformed
        String marca = txt_marca.getText().trim();
        String numeroSerie = txt_numero_serie.getText().trim().toUpperCase();
        String tipo = txt_tipo.getText().trim();  // ← también se agrega .trim()
        String estado = (String) cmb_estado.getSelectedItem();

        // ── Validación campos vacíos ────────────────────────────────────────
        if (marca.isEmpty() || numeroSerie.isEmpty() || tipo.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos obligatorios (Tipo, Marca y N° Serie).",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            if (tipo.isEmpty()) {
                txt_tipo.requestFocus();  // enfoca el campo vacío
            }
            return;
        }

        // ── Validación formato número de serie ──────────────────────────────
        if (!numeroSerie.matches("[A-Z0-9\\-]{4,30}")) {
            JOptionPane.showMessageDialog(this,
                    "El N° de serie solo puede contener letras, números y guiones (-).\n"
                    + "Mínimo 4 caracteres, máximo 30.",
                    "Formato inválido", JOptionPane.WARNING_MESSAGE);
            txt_numero_serie.requestFocus();
            return;
        }

        // ── Validación número de serie duplicado ────────────────────────────
        if (daoEquipo.existeNumeroSerie(numeroSerie)) {
            JOptionPane.showMessageDialog(this,
                    "El número de serie \"" + numeroSerie + "\" ya existe en el sistema.",
                    "N° Serie duplicado", JOptionPane.WARNING_MESSAGE);
            txt_numero_serie.requestFocus();
            return;
        }

        // ── Crear equipo ────────────────────────────────────────────────────
        EquipoOficina eq = new EquipoOficina();
        eq.setTipo(tipo);
        eq.setMarca(marca.toUpperCase());
        eq.setNumeroSerie(numeroSerie);
        eq.setEstado(estado);

        daoEquipo.create(eq);

        JOptionPane.showMessageDialog(this, "Equipo registrado correctamente.");
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_bt_registrar_equipoActionPerformed
    /**
     * Maneja el evento del botón "Modificar". Actualiza los datos del equipo
     * seleccionado en la base de datos.
     * <p>
     * Realiza las siguientes operaciones:
     * <ul>
     * <li>Busca el equipo por su ID usando
     * {@link DAOEquipoOficina#buscarPorId(int)}.</li>
     * <li>Verifica que los campos obligatorios no estén vacíos.</li>
     * <li>Verifica que el N° de serie no esté duplicado (excluyendo el equipo
     * actual).</li>
     * <li>Actualiza los campos y persiste los cambios con
     * {@link DAOEquipoOficina#update(EquipoOficina)}.</li>
     * <li>Recarga la tabla y limpia el formulario tras la actualización
     * exitosa.</li>
     * </ul>
     *
     * @param evt Evento de acción generado por el botón bt_modificar_equipo.
     */
    private void bt_modificar_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificar_equipoActionPerformed
        Integer idSeleccionado = Integer.parseInt(txt_id_equipo.getText());

        EquipoOficina eq = daoEquipo.buscarPorId(idSeleccionado);
        if (eq == null) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró el equipo a modificar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String marca = txt_marca.getText().trim();
        String numeroSerie = txt_numero_serie.getText().trim().toUpperCase();
        String tipo = (String) txt_tipo.getText();
        String estado = (String) cmb_estado.getSelectedItem();

// ── Validación campos vacíos ────────────────────────────────────────
        if (marca.isEmpty() || numeroSerie.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos obligatorios (Marca y N° Serie).",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

// ── Validación formato número de serie ──────────────────────────────
        if (!numeroSerie.matches("[A-Z0-9\\-]{4,30}")) {
            JOptionPane.showMessageDialog(this,
                    "El N° de serie solo puede contener letras, números y guiones (-).\n"
                    + "Mínimo 4 caracteres, máximo 30.",
                    "Formato inválido", JOptionPane.WARNING_MESSAGE);
            txt_numero_serie.requestFocus();
            return;
        }

// ── Validación N° serie duplicado (excluye el equipo actual) ────────
        if (!numeroSerie.equals(eq.getNumeroSerie()) && daoEquipo.existeNumeroSerie(numeroSerie)) {
            JOptionPane.showMessageDialog(this,
                    "El número de serie \"" + numeroSerie + "\" ya pertenece a otro equipo.",
                    "N° Serie duplicado", JOptionPane.WARNING_MESSAGE);
            txt_numero_serie.requestFocus();
            return;
        }
        // ── Validación campos vacíos ────────────────────────────────────────
        if (marca.isEmpty() || numeroSerie.isEmpty() || tipo.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos obligatorios (Tipo, Marca y N° Serie).",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            if (tipo.isEmpty()) {
                txt_tipo.requestFocus();  // enfoca el campo vacío
            }
            return;
        }

// ── Aplicar cambios ─────────────────────────────────────────────────
        eq.setTipo(tipo);
        eq.setMarca(marca);
        eq.setNumeroSerie(numeroSerie);
        eq.setEstado(estado);

        daoEquipo.update(eq);

        JOptionPane.showMessageDialog(this, "Equipo modificado correctamente.");
        cargarTabla();
        activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_modificar_equipoActionPerformed

    /**
     * Maneja el evento del botón "Eliminar". Elimina el equipo seleccionado de
     * la base de datos tras confirmar con el usuario.
     *
     * @param evt Evento de acción generado por el botón bt_eliminar_equipo.
     */
    private void bt_eliminar_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminar_equipoActionPerformed
        Integer idSeleccionado = Integer.parseInt(this.txt_id_equipo.getText());

        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar este equipo?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            daoEquipo.delete(idSeleccionado);
            JOptionPane.showMessageDialog(this, "Equipo eliminado correctamente.");
            activarModoNuevo();
            cargarTabla();
            limpiarFormulario();
        }
    }//GEN-LAST:event_bt_eliminar_equipoActionPerformed

    private void bt_actualizar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_pestañaActionPerformed
        cargarTabla();
    }//GEN-LAST:event_bt_actualizar_pestañaActionPerformed

    private void bt_cerrar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrar_pestañaActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cerrar_pestañaActionPerformed

    private void txt_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoActionPerformed

    /**
     * Activa el modo edición en el formulario, habilitando los botones de
     * cancelar, modificar y eliminar, y deshabilitando el botón de registrar.
     */
    private void activarModoEditar() {
        this.bt_cancelar.setEnabled(true);
        this.bt_modificar_equipo.setEnabled(true);
        this.bt_eliminar_equipo.setEnabled(true);
        this.bt_registrar_equipo.setEnabled(false);
    }

    /**
     * Activa el modo nuevo para ingresar un equipo.
     */
    private void activarModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_modificar_equipo.setEnabled(false);
        this.bt_eliminar_equipo.setEnabled(false);
        this.bt_registrar_equipo.setEnabled(true);
    }

    DAOEquipoOficina daoEquipo = new DAOEquipoOficina();
    
    
    private void aplicarEstilos() {

    // Paleta "Deep Ocean" ─────────────────────────────────────────────────
    final java.awt.Color BG_PRIMARY   = new java.awt.Color( 10,  25,  47); // #0A192F  marino profundo
    final java.awt.Color BG_SECONDARY = new java.awt.Color( 23,  42,  69); // #172A45  azul oscuro
    final java.awt.Color BG_FIELD     = new java.awt.Color( 31,  52,  96); // #1F3460  azul medio
    final java.awt.Color ACCENT_MINT  = new java.awt.Color(100, 255, 218); // #64FFDA  menta brillante
    final java.awt.Color ACCENT_BLUE  = new java.awt.Color( 87, 203, 242); // #57CBF2  celeste
    final java.awt.Color TEXT_LIGHT   = new java.awt.Color(204, 214, 246); // #CCD6F6  blanco lavanda
    final java.awt.Color BTN_DELETE   = new java.awt.Color(255, 107, 107); // #FF6B6B  rojo coral
    final java.awt.Color BTN_NEUTRAL  = new java.awt.Color(136, 146, 176); // #8892B0  gris azulado
    final java.awt.Color ROW_ODD      = new java.awt.Color( 17,  34,  64); // #112240
    final java.awt.Color ROW_EVEN     = new java.awt.Color( 10,  25,  47); // #0A192F
    final java.awt.Color ROW_SEL      = new java.awt.Color( 31,  52,  96); // #1F3460

    // Fuentes ─────────────────────────────────────────────────────────────
    java.awt.Font fLabel  = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
    java.awt.Font fField  = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12);
    java.awt.Font fBtn    = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
    java.awt.Font fTable  = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12);
    java.awt.Font fHeader = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);

    // Content pane ────────────────────────────────────────────────────────
    getContentPane().setBackground(BG_PRIMARY);

    // Labels ──────────────────────────────────────────────────────────────
    for (javax.swing.JLabel lbl : new javax.swing.JLabel[]{
            jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6}) {
        lbl.setForeground(TEXT_LIGHT);
        lbl.setFont(fLabel);
    }

    // Campos de texto ─────────────────────────────────────────────────────
    javax.swing.border.Border fieldBorder = javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(ACCENT_MINT, 1, true),
        javax.swing.BorderFactory.createEmptyBorder(3, 6, 3, 6));

    for (javax.swing.JTextField tf : new javax.swing.JTextField[]{
            txt_id_equipo, txt_tipo, txt_marca, txt_numero_serie}) {
        tf.setBackground(BG_FIELD);
        tf.setForeground(TEXT_LIGHT);
        tf.setCaretColor(ACCENT_MINT);
        tf.setFont(fField);
        tf.setBorder(fieldBorder);
    }
    // ID: fondo más apagado (campo de solo lectura visual)
    txt_id_equipo.setBackground(BG_SECONDARY);

    // ComboBox ────────────────────────────────────────────────────────────
    cmb_estado.setBackground(BG_FIELD);
    cmb_estado.setForeground(TEXT_LIGHT);
    cmb_estado.setFont(fField);

    // Botones (código de colores por función) ─────────────────────────────
    // Verde menta  → registrar / acción principal
    estilizarBoton(bt_registrar_equipo, ACCENT_MINT,
                   new java.awt.Color(10, 25, 47), fBtn);

    // Celeste      → modificar
    estilizarBoton(bt_modificar_equipo, ACCENT_BLUE,
                   new java.awt.Color(10, 25, 47), fBtn);

    // Rojo coral   → eliminar
    estilizarBoton(bt_eliminar_equipo, BTN_DELETE,
                   java.awt.Color.WHITE, fBtn);

    // Gris azulado → cancelar
    estilizarBoton(bt_cancelar, BTN_NEUTRAL,
                   java.awt.Color.WHITE, fBtn);

    // Oscuro con borde menta → actualizar pestaña
    estilizarBoton(bt_actualizar_pestaña, BG_SECONDARY, ACCENT_MINT, fBtn);
    bt_actualizar_pestaña.setBorderPainted(true);
    bt_actualizar_pestaña.setBorder(
        javax.swing.BorderFactory.createLineBorder(ACCENT_MINT, 1, true));

    // Oscuro con borde rojo  → cerrar pestaña
    estilizarBoton(bt_cerrar_pestaña,
                   new java.awt.Color(60, 15, 15), BTN_DELETE, fBtn);
    bt_cerrar_pestaña.setBorderPainted(true);
    bt_cerrar_pestaña.setBorder(
        javax.swing.BorderFactory.createLineBorder(BTN_DELETE, 1, true));

    // Tabla ───────────────────────────────────────────────────────────────
    tbl_equipos_oficina.setBackground(ROW_ODD);
    tbl_equipos_oficina.setForeground(TEXT_LIGHT);
    tbl_equipos_oficina.setFont(fTable);
    tbl_equipos_oficina.setGridColor(BG_SECONDARY);
    tbl_equipos_oficina.setRowHeight(26);
    tbl_equipos_oficina.setSelectionBackground(ROW_SEL);
    tbl_equipos_oficina.setSelectionForeground(ACCENT_MINT);
    tbl_equipos_oficina.setShowHorizontalLines(true);
    tbl_equipos_oficina.setShowVerticalLines(false);
    tbl_equipos_oficina.setIntercellSpacing(new java.awt.Dimension(0, 1));

    // Encabezado de tabla
    javax.swing.table.JTableHeader tableHeader = tbl_equipos_oficina.getTableHeader();
    tableHeader.setBackground(new java.awt.Color(17, 34, 64));
    tableHeader.setForeground(ACCENT_MINT);
    tableHeader.setFont(fHeader);
    tableHeader.setReorderingAllowed(false);
    ((javax.swing.table.DefaultTableCellRenderer) tableHeader.getDefaultRenderer())
        .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    // Renderer con filas alternas
    tbl_equipos_oficina.setDefaultRenderer(Object.class,
        new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable t, Object val, boolean sel,
                    boolean focus, int row, int col) {
                super.getTableCellRendererComponent(t, val, sel, focus, row, col);
                if (sel) {
                    setBackground(ROW_SEL);
                    setForeground(ACCENT_MINT);
                } else {
                    setBackground(row % 2 == 0 ? ROW_EVEN : ROW_ODD);
                    setForeground(TEXT_LIGHT);
                }
                setFont(fTable);
                setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
                return this;
            }
        });

    // ScrollPane ──────────────────────────────────────────────────────────
    jScrollPane1.getViewport().setBackground(ROW_EVEN);
    jScrollPane1.setBorder(
        javax.swing.BorderFactory.createLineBorder(ACCENT_MINT, 1, true));
}

// ── Método auxiliar reutilizable ─────────────────────────────────────────
private void estilizarBoton(javax.swing.JButton btn,
                             java.awt.Color bg,
                             java.awt.Color fg,
                             java.awt.Font font) {
    btn.setBackground(bg);
    btn.setForeground(fg);
    btn.setFont(font);
    btn.setFocusPainted(false);
    btn.setBorderPainted(false);
    btn.setOpaque(true);
    btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar_equipo;
    private javax.swing.JButton bt_modificar_equipo;
    private javax.swing.JButton bt_registrar_equipo;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_equipos_oficina;
    private javax.swing.JTextField txt_id_equipo;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_numero_serie;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
