/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOMantenimiento;
import com.mycompany.transporte_mercancia.Logica.Camion;
import javax.swing.table.DefaultTableModel;
import com.mycompany.transporte_mercancia.Data.DAOCamion;
import com.mycompany.transporte_mercancia.Logica.Personal;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author saave
 */
public class FrmKilometraje extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmKilometraje
     */
    private Personal conductorActivo;

    public FrmKilometraje(Personal personal) {
        initComponents();
        this.conductorActivo = personal;
        cargarTabla();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_camiones = new javax.swing.JTable();
        txt_kilo_total = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bt_agregar_kilo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_id_camion = new javax.swing.JTextField();
        bt_actualizar_pestaña = new javax.swing.JButton();
        bt_cerrar_pestaña = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        tbl_camiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_camiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_camionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_camiones);

        txt_kilo_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kilo_totalActionPerformed(evt);
            }
        });

        jLabel1.setText("Kilometraje Total");

        bt_agregar_kilo.setText("Agregar kilometraje");
        bt_agregar_kilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregar_kiloActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Camion");

        txt_id_camion.setEditable(false);

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 102, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(250, 250, 250))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_agregar_kilo)
                                .addGap(104, 104, 104))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_actualizar_pestaña)
                                .addGap(13, 13, 13)
                                .addComponent(bt_cerrar_pestaña))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kilo_total, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_id_camion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txt_id_camion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_kilo_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43)
                        .addComponent(bt_agregar_kilo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_actualizar_pestaña)
                        .addComponent(bt_cerrar_pestaña)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kilo_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kilo_totalActionPerformed

    }//GEN-LAST:event_txt_kilo_totalActionPerformed
    /**
     * Maneja el evento del botón "Agregar Kilometraje". Actualiza el
     * kilometraje total del camión seleccionado en la base de datos.
     * <p>
     * Realiza las siguientes operaciones:
     * <ul>
     * <li>Verifica que se haya seleccionado un camión (campo ID no vacío).</li>
     * <li>Determina la lista de camiones según si hay un conductor activo o
     * no.</li>
     * <li>Valida que el kilometraje ingresado sea un número no negativo.</li>
     * <li>Actualiza el camión con {@link DAOCamion#update(Camion)}.</li>
     * <li>Si el kilometraje es ≥ 5000 km y no hay mantenimiento programado,
     * muestra una alerta de mantenimiento.</li>
     * <li>Recarga la tabla y limpia el formulario tras el registro
     * exitoso.</li>
     * </ul>
     *
     * @param evt Evento de acción generado por el botón bt_agregar_kilo.
     */
    private void bt_agregar_kiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregar_kiloActionPerformed

        if (this.txt_id_camion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un camión");
            return;
        }

        Integer id_seleccionado = Integer.parseInt(this.txt_id_camion.getText());
        Camion c = null;

        List<Camion> lista = (conductorActivo != null && conductorActivo.getRol().equals("conductor"))
                ? dp.listarPorConductor(conductorActivo.getIdPersonal())
                : dp.listarTodos();

        for (Camion c_busqueda : lista) {
            if (c_busqueda.getIdCamion() == id_seleccionado) {
                c = c_busqueda;
                break;
            }
        }

        try {
            String texto = this.txt_kilo_total.getText().trim();
            int kilometraje = Integer.parseInt(texto);

            if (kilometraje < 0) {
                JOptionPane.showMessageDialog(null, "Kilometraje no puede ser negativo");
                return;
            }

            c.setKilometrajeTotal(kilometraje);
            dp.update(c);

            if (kilometraje >= 5000) {
                DAOMantenimiento dm = new DAOMantenimiento();
                if (!dm.tieneMantenimientoActivo(c.getIdCamion())) {
                    JOptionPane.showMessageDialog(
                            null,
                            "⚠️ El camión " + c.getMatricula() + " ha alcanzado " + kilometraje + " km.\n"
                            + "¡Requiere mantenimiento!",
                            "Alerta de Mantenimiento",
                            JOptionPane.WARNING_MESSAGE
                    );
                }
            }
            JOptionPane.showMessageDialog(null, "Kilometraje registrado correctamente");

            cargarTabla();
            limpiarFormulario();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe ingresar solo números");
        }

    }//GEN-LAST:event_bt_agregar_kiloActionPerformed
    /**
     * Limpia los campos de entrada del formulario de kilometraje,
     * restableciendo el campo de kilometraje total y el ID del camión a vacío.
     */
    private void limpiarFormulario() {

        this.txt_kilo_total.setText("");
        this.txt_id_camion.setText("");

    }

    /**
     * Maneja el evento de clic sobre una fila de la tabla de camiones. Recupera
     * el ID del camión seleccionado, lo muestra en {@code txt_id_camion} y
     * carga el kilometraje actual del camión en {@code txt_kilo_total}.
     * <p>
     * La lista de camiones consultada depende de si hay un conductor activo: si
     * lo hay, se muestran solo sus camiones asignados; de lo contrario, se
     * muestran todos.
     *
     * @param evt Evento de ratón generado al hacer clic en la tabla
     * tbl_camiones.
     */
    private void tbl_camionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_camionesMouseClicked
        int selectedRow = this.tbl_camiones.getSelectedRow();
        if (selectedRow != -1) {

            Object cellValue = this.tbl_camiones.getValueAt(selectedRow, 0);

            Integer id_seleccionado = (Integer) cellValue;
            this.txt_id_camion.setText(id_seleccionado.toString());

            List<Camion> lista = (conductorActivo != null && conductorActivo.getRol().equals("conductor"))
                    ? dp.listarPorConductor(conductorActivo.getIdPersonal())
                    : dp.listarTodos();

            for (Camion c : lista) {
                if (c.getIdCamion() == id_seleccionado) {
                    this.txt_kilo_total.setText(c.getKilometrajeTotal().toString());
                }

            }
    }//GEN-LAST:event_tbl_camionesMouseClicked
    }

    /**
     * Carga y actualiza la tabla {@code tbl_camiones} con los camiones
     * disponibles.
     * <p>
     * Si existe un conductor activo con rol "conductor", muestra únicamente los
     * camiones asignados a él mediante
     * {@link DAOCamion#listarPorConductor(int)}. De lo contrario, muestra todos
     * los camiones con {@link DAOCamion#listarTodos()}.
     * <p>
     * Las columnas mostradas son: ID, Marca, Modelo, Año y Matrícula.
     */
    public void cargarTabla() {
        Object[] nombresColumnas = {"id", "Marca", "Modelo", "Año", "Matrícula"};
        DefaultTableModel modelo = new DefaultTableModel(nombresColumnas, 0);

        List<Camion> lista = (conductorActivo != null && conductorActivo.getRol().equals("conductor"))
                ? dp.listarPorConductor(conductorActivo.getIdPersonal())
                : dp.listarTodos();

        for (Camion c : lista) {
            Object[] row1 = {c.getIdCamion(), c.getMarca(), c.getModelo(), c.getAnio(), c.getMatricula()};
            modelo.addRow(row1);
        }

        this.tbl_camiones.setModel(modelo);
    }

    /**
     * Objeto de acceso a datos para operaciones CRUD sobre {@link Camion}.
     */
    DAOCamion dp = new DAOCamion();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_agregar_kilo;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_camiones;
    private javax.swing.JTextField txt_id_camion;
    private javax.swing.JTextField txt_kilo_total;
    // End of variables declaration//GEN-END:variables
}
