/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOEquipoOficina;
import com.mycompany.transporte_mercancia.Data.DAOMantenimientoEquipo;
import com.mycompany.transporte_mercancia.Logica.EquipoOficina;
import com.mycompany.transporte_mercancia.Logica.MantenimientoEquipo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmMantenimientoEquipos extends javax.swing.JInternalFrame {

    DAOMantenimientoEquipo daoMant = new DAOMantenimientoEquipo();
    DAOEquipoOficina daoEquipo = new DAOEquipoOficina();

    /**
     * Creates new form FrmMantenimientoEquipos
     */
    public FrmMantenimientoEquipos() {
        initComponents();
        cargarTabla();
        cargarComboEquipo();
        cargarComboTipo();
        cargarComboEstado();
        bt_actualizar_pestaña.addActionListener(e -> {
            cargarTabla();
            cargarComboEquipo();
        });
        bt_cerrar_pestaña.addActionListener(e -> dispose());
        activarModoNuevo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        txt_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mantenimientos = new javax.swing.JTable();
        cmb_equipo = new javax.swing.JComboBox<>();
        cmb_tipo = new javax.swing.JComboBox<>();
        dc_fecha_entrada = new com.toedter.calendar.JDateChooser();
        bt_registrar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();
        bt_cerrar_pestaña = new javax.swing.JButton();
        cmb_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("ID");

        jLabel2.setText("Equipo");

        jLabel3.setText("Tipo Mantenimiento");

        jLabel4.setText("Fecha ingreso");

        jLabel6.setText("Descripcion");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        tbl_mantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mantenimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mantenimientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_mantenimientos);

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));

        bt_registrar.setText("Registrar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");
        bt_actualizar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_pestañaActionPerformed(evt);
            }
        });

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");
        bt_cerrar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrar_pestañaActionPerformed(evt);
            }
        });

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En progreso", "Postergado", "Terminado" }));

        jLabel7.setText("Estado");

        jLabel5.setText("Registro Mantenimiento");

        jLabel8.setText("Registro repuestos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_actualizar_pestaña)
                        .addGap(30, 30, 30)
                        .addComponent(bt_cerrar_pestaña)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(bt_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(16, 315, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_actualizar_pestaña)
                    .addComponent(bt_cerrar_pestaña)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_modificar)
                            .addComponent(bt_registrar)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarComboEquipo() {
        cmb_equipo.removeAllItems();
        for (EquipoOficina e : new DAOEquipoOficina().listarOperativos()) {
            cmb_equipo.addItem(e.getIdEquipo() + " - " + e.getTipo() + " - " + e.getNumeroSerie());
        }
    }

    public void cargarComboTipo() {
        cmb_tipo.removeAllItems();
        cmb_tipo.addItem("Preventivo");
        cmb_tipo.addItem("Correctivo");
    }

    public void cargarComboEstado() {
        cmb_estado.removeAllItems();
        cmb_estado.addItem("En progreso");
        cmb_estado.addItem("Postergado");
        cmb_estado.addItem("Terminado");
    }

    private int obtenerIdEquipoSeleccionado() {
        String seleccion = (String) cmb_equipo.getSelectedItem();
        return Integer.parseInt(seleccion.split(" - ")[0].trim());
    }


    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void tbl_mantenimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mantenimientosMouseClicked
        int fila = tbl_mantenimientos.getSelectedRow();
        if (fila == -1) {
            return;
        }

        int idMant = (Integer) tbl_mantenimientos.getValueAt(fila, 0);
        txt_id.setText(String.valueOf(idMant));

        MantenimientoEquipo m = daoMant.buscarPorId(idMant);
        if (m == null) {
            return;
        }

        // Cargar equipo en combo (incluye los que están en mantención)
        cargarComboEquipoEdicion(m.getIdEquipo());

        cmb_tipo.setSelectedItem(m.getTipoMantenimiento());
        cmb_estado.setSelectedItem(m.getEstado());
        dc_fecha_entrada.setDate(new java.util.Date(m.getFechaEntrada().getTime()));
        txt_descripcion.setText(m.getDescripcion());

        // Si ya está Terminado, bloquear todos los campos
        if ("Terminado".equals(m.getEstado())) {
            activarModoTerminado();
        } else {
            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_mantenimientosMouseClicked
    private void cargarComboEquipoEdicion(int idEquipoActual) {
        cmb_equipo.removeAllItems();

        // Agregar el equipo actual (que puede estar en mantención)
        EquipoOficina equipoActual = daoEquipo.buscarPorId(idEquipoActual);
        if (equipoActual != null) {
            cmb_equipo.addItem(equipoActual.getIdEquipo() + " - "
                    + equipoActual.getTipo() + " - " + equipoActual.getNumeroSerie());
        }

        // Agregar los demás operativos que no sean el mismo
        for (EquipoOficina e : daoEquipo.listarOperativos()) {
            if (e.getIdEquipo() != idEquipoActual) {
                cmb_equipo.addItem(e.getIdEquipo() + " - " + e.getTipo() + " - " + e.getNumeroSerie());
            }
        }

        // Seleccionar el actual
        cmb_equipo.setSelectedIndex(0);
    }
    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        if (cmb_equipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay equipos operativos disponibles.",
                    "Sin equipos", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (dc_fecha_entrada.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar la fecha de inicio del mantenimiento.",
                    "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (txt_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripción del mantenimiento.",
                    "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MantenimientoEquipo m = new MantenimientoEquipo();
        m.setIdEquipo         (obtenerIdEquipoSeleccionado());
        m.setTipoMantenimiento((String) cmb_tipo.getSelectedItem());
        m.setEstado           ("En progreso"); // siempre inicia en progreso
        m.setFechaEntrada     (new java.sql.Date(dc_fecha_entrada.getDate().getTime()));
        m.setDescripcion      (txt_descripcion.getText().trim());

        if (daoMant.create(m)) {
            JOptionPane.showMessageDialog(this, "Mantenimiento registrado correctamente.");
            cargarTabla();
            cargarComboEquipo();
            limpiarFormulario();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Error al registrar el mantenimiento.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
       if (txt_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripción.",
                    "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String estadoNuevo = (String) cmb_estado.getSelectedItem();

        // Confirmación especial al terminar
        if ("Terminado".equals(estadoNuevo)) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Está seguro de marcar este mantenimiento como TERMINADO?\n"
                  + "Esta acción no se puede deshacer.",
                    "Confirmar cierre", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm != JOptionPane.YES_OPTION) return;
        }

        MantenimientoEquipo m = new MantenimientoEquipo();
        m.setIdMantenimiento  (Integer.parseInt(txt_id.getText()));
        m.setIdEquipo         (obtenerIdEquipoSeleccionado());
        m.setTipoMantenimiento((String) cmb_tipo.getSelectedItem());
        m.setEstado           (estadoNuevo);
        m.setFechaEntrada     (new java.sql.Date(dc_fecha_entrada.getDate().getTime()));
        m.setDescripcion      (txt_descripcion.getText().trim());

        if (daoMant.update(m)) {
            String mensaje = "Mantenimiento actualizado correctamente.";
            if ("Terminado".equals(estadoNuevo)) {
                // Calcular días finales para mostrar en mensaje
                MantenimientoEquipo actualizado = daoMant.buscarPorId(m.getIdMantenimiento());
                if (actualizado != null) {
                    mensaje = "¡Mantenimiento cerrado exitosamente!\n"
                            + "Días activos totales: " + actualizado.getDiasActivos() + " día(s).";
                }
            }
            JOptionPane.showMessageDialog(this, mensaje);
            cargarTabla();
            cargarComboEquipo();
            limpiarFormulario();
            activarModoNuevo();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar. Recuerda que los mantenimientos\n"
                  + "en estado 'Terminado' no se pueden modificar.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        int idMant = Integer.parseInt(txt_id.getText());
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este registro de mantenimiento?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (daoMant.delete(idMant)) {
                JOptionPane.showMessageDialog(this, "Mantenimiento eliminado.");
                cargarTabla();
                cargarComboEquipo();
                limpiarFormulario();
                activarModoNuevo();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error al eliminar el mantenimiento.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
        cargarComboEquipo();
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_cerrar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrar_pestañaActionPerformed
       dispose();
    }//GEN-LAST:event_bt_cerrar_pestañaActionPerformed

    private void bt_actualizar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_pestañaActionPerformed
        cargarTabla();
        cargarComboEquipo();
    }//GEN-LAST:event_bt_actualizar_pestañaActionPerformed
   
    
    public void cargarTabla() {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // ← agregar esto

    Object[] columnas = {"ID", "ID Equipo", "Tipo Mant.", "Estado",
                         "Fecha Inicio", "Fecha Fin", "Días Activos", "Descripción"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };

    for (MantenimientoEquipo m : daoMant.listarTodos()) {
        Object[] fila = {
            m.getIdMantenimiento(),
            m.getIdEquipo(),
            m.getTipoMantenimiento(),
            m.getEstado(),
            m.getFechaEntrada() != null ? sdf.format(m.getFechaEntrada()) : "—",
            m.getFechaFin()     != null ? sdf.format(m.getFechaFin())     : "—", 
            m.getDiasActivos() + " día(s)",
            m.getDescripcion()
        };
        modelo.addRow(fila);
    }
    tbl_mantenimientos.setModel(modelo);
}

    private void limpiarFormulario() {
        txt_id.setText("");
        txt_descripcion.setText("");
        dc_fecha_entrada.setDate(null);
        cmb_estado.setSelectedIndex(0); // "En progreso"
    }

    private void activarModoNuevo() {
        bt_registrar.setEnabled(true);
        bt_modificar.setEnabled(false);
        bt_eliminar .setEnabled(false);
        bt_cancelar .setEnabled(false);
        cmb_estado  .setEnabled(false); // al crear siempre es "En progreso"
        cmb_equipo  .setEnabled(true);
        dc_fecha_entrada.setEnabled(true);
    }

    private void activarModoEditar() {
        bt_registrar.setEnabled(false);
        bt_modificar.setEnabled(true);
        bt_eliminar .setEnabled(true);
        bt_cancelar .setEnabled(true);
        cmb_estado  .setEnabled(true);  // en edición sí se puede cambiar
        cmb_equipo  .setEnabled(false); // no se cambia el equipo en edición
        dc_fecha_entrada.setEnabled(false); // fecha de inicio es fija
    }

    private void activarModoTerminado() {
        bt_registrar.setEnabled(false);
        bt_modificar.setEnabled(false);  // bloqueado: ya terminó
        bt_eliminar .setEnabled(true);   // se puede eliminar el registro si se necesita
        bt_cancelar .setEnabled(true);
        cmb_estado  .setEnabled(false);
        cmb_equipo  .setEnabled(false);
        dc_fecha_entrada.setEnabled(false);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_equipo;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JComboBox<String> cmb_tipo;
    private com.toedter.calendar.JDateChooser dc_fecha_entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_mantenimientos;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
