/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOEquipoOficina;
import com.mycompany.transporte_mercancia.Data.DAOMantenimientoEquipo;
import com.mycompany.transporte_mercancia.Logica.EquipoOficina;
import com.mycompany.transporte_mercancia.Logica.MantenimientoEquipo;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmMantenimientoEquipos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMantenimientoEquipos
     */
    public FrmMantenimientoEquipos() {
        initComponents();
        cargarTabla();
        cargarComboEquipo();
        cargarComboTipo();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        txt_id = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mantenimientos = new javax.swing.JTable();
        cmb_equipo = new javax.swing.JComboBox<>();
        cmb_tipo = new javax.swing.JComboBox<>();
        dc_fecha_entrada = new com.toedter.calendar.JDateChooser();
        dc_fecha_salida = new com.toedter.calendar.JDateChooser();
        bt_registrar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();
        bt_cerrar_pestaña = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setText("Equipo");

        jLabel3.setText("Tipo Mantenimiento");

        jLabel4.setText("Fecha ingreso");

        jLabel5.setText("Fecha salida");

        jLabel6.setText("Descripcion");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        txt_id.setEditable(false);
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        tbl_mantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mantenimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mantenimientosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_mantenimientos);

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));

        bt_registrar.setText("Registrar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");
        bt_actualizar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_actualizar_pestañaActionPerformed(evt);
            }
        });

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");
        bt_cerrar_pestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrar_pestañaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(74, 74, 74))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(84, 84, 84)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dc_fecha_salida, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_eliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_cancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_registrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_modificar)))
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_equipo, 0, 107, Short.MAX_VALUE)
                            .addComponent(txt_id))
                        .addGap(154, 154, 154)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_actualizar_pestaña)
                .addGap(30, 30, 30)
                .addComponent(bt_cerrar_pestaña)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_actualizar_pestaña)
                            .addComponent(bt_cerrar_pestaña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmb_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dc_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar)
                            .addComponent(bt_modificar))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar))))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void cargarComboEquipo() {
        cmb_equipo.removeAllItems();
        ArrayList<EquipoOficina> lista = new DAOEquipoOficina().listarOperativos(); // <-- cambio aquí
        for (EquipoOficina e : lista) {
            cmb_equipo.addItem(e.getIdEquipo() + " - " + e.getTipo() + " - " + e.getNumeroSerie());
        }
    }

// ══════════════════════════════════════════════════════════════
// CARGAR COMBO TIPO MANTENIMIENTO
// ══════════════════════════════════════════════════════════════
    public void cargarComboTipo() {
        cmb_tipo.removeAllItems();
        cmb_tipo.addItem("Preventivo");
        cmb_tipo.addItem("Correctivo");
    }

    private int obtenerIdEquipoSeleccionado() {
        String seleccion = (String) cmb_equipo.getSelectedItem();
        // El formato es "ID - TIPO - SERIE", extraemos el ID antes del primer " - "
        return Integer.parseInt(seleccion.split(" - ")[0].trim());
    }


    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void tbl_mantenimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mantenimientosMouseClicked
        int fila = tbl_mantenimientos.getSelectedRow();
        if (fila != -1) {
            int idMant = (Integer) tbl_mantenimientos.getValueAt(fila, 0);
            txt_id.setText(String.valueOf(idMant));

            for (MantenimientoEquipo m : daoMant.listarTodos()) {
                if (m.getIdMantenimiento() == idMant) {
                    // Buscar y seleccionar el equipo en el combo
                    for (int i = 0; i < cmb_equipo.getItemCount(); i++) {
                        if (cmb_equipo.getItemAt(i).startsWith(m.getIdEquipo() + " - ")) {
                            cmb_equipo.setSelectedIndex(i);
                            break;
                        }
                    }
                    cmb_tipo.setSelectedItem(m.getTipoMantenimiento());
                    dc_fecha_entrada.setDate(new java.util.Date(m.getFechaEntrada().getTime()));
                    dc_fecha_salida.setDate(new java.util.Date(m.getFechaSalida().getTime()));
                    txt_descripcion.setText(m.getDescripcion());
                }
            }
            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_mantenimientosMouseClicked

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        // Validar que haya equipo seleccionado
        if (cmb_equipo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay equipos registrados. Debe registrar un equipo primero.",
                    "Equipo no encontrado", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar fechas no nulas
        if (dc_fecha_entrada.getDate() == null || dc_fecha_salida.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar ambas fechas.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Date fechaEntrada = new java.sql.Date(dc_fecha_entrada.getDate().getTime());
        java.sql.Date fechaSalida = new java.sql.Date(dc_fecha_salida.getDate().getTime());

        // Validar orden de fechas
        if (!fechaSalida.after(fechaEntrada)) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de salida debe ser posterior a la fecha de entrada.",
                    "Error de fechas", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar descripción
        if (txt_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe ingresar una descripción del mantenimiento.",
                    "Campo vacío", JOptionPane.WARNING_MESSAGE);
            return;
        }

        MantenimientoEquipo m = new MantenimientoEquipo();
        m.setIdEquipo(obtenerIdEquipoSeleccionado());
        m.setTipoMantenimiento((String) cmb_tipo.getSelectedItem());
        m.setFechaEntrada(fechaEntrada);
        m.setFechaSalida(fechaSalida);
        m.setDescripcion(txt_descripcion.getText().trim());

        daoMant.create(m);
        JOptionPane.showMessageDialog(this, "Mantenimiento registrado correctamente.");
        cargarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_bt_registrarActionPerformed

    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        if (dc_fecha_entrada.getDate() == null || dc_fecha_salida.getDate() == null) {
            JOptionPane.showMessageDialog(this,
                    "Debe seleccionar ambas fechas.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.sql.Date fechaEntrada = new java.sql.Date(dc_fecha_entrada.getDate().getTime());
        java.sql.Date fechaSalida = new java.sql.Date(dc_fecha_salida.getDate().getTime());

        if (!fechaSalida.after(fechaEntrada)) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de salida debe ser posterior a la fecha de entrada.",
                    "Error de fechas", JOptionPane.ERROR_MESSAGE);
            return;
        }

        MantenimientoEquipo m = new MantenimientoEquipo();
        m.setIdMantenimiento(Integer.parseInt(txt_id.getText()));
        m.setIdEquipo(obtenerIdEquipoSeleccionado());
        m.setTipoMantenimiento((String) cmb_tipo.getSelectedItem());
        m.setFechaEntrada(fechaEntrada);
        m.setFechaSalida(fechaSalida);
        m.setDescripcion(txt_descripcion.getText().trim());

        daoMant.update(m);
        JOptionPane.showMessageDialog(this, "Mantenimiento modificado correctamente.");
        cargarTabla();
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_modificarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        int idMant = Integer.parseInt(txt_id.getText());
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este registro?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            daoMant.delete(idMant);
            JOptionPane.showMessageDialog(this, "Mantenimiento eliminado.");
            cargarTabla();
            limpiarFormulario();
            activarModoNuevo();
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_cerrar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrar_pestañaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cerrar_pestañaActionPerformed

    private void bt_actualizar_pestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_actualizar_pestañaActionPerformed
        cargarTabla();
        cargarComboEquipo();
    }//GEN-LAST:event_bt_actualizar_pestañaActionPerformed
    public void cargarTabla() {
        Object[] columnas = {"ID", "ID Equipo", "Tipo Mant.", "Entrada", "Salida", "Descripción"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (MantenimientoEquipo m : daoMant.listarTodos()) {
            Object[] fila = {
                m.getIdMantenimiento(),
                m.getIdEquipo(),
                m.getTipoMantenimiento(),
                m.getFechaEntrada(),
                m.getFechaSalida(),
                m.getDescripcion()
            };
            modelo.addRow(fila);
        }
        tbl_mantenimientos.setModel(modelo);
    }

    private void limpiarFormulario() {
        txt_id.setText("");
        txt_descripcion.setText("");
        dc_fecha_entrada.setDate(null);
        dc_fecha_salida.setDate(null);
    }

    private void activarModoEditar() {
        bt_cancelar.setEnabled(true);
        bt_modificar.setEnabled(true);
        bt_eliminar.setEnabled(true);
        bt_registrar.setEnabled(false);
    }

    private void activarModoNuevo() {
        bt_cancelar.setEnabled(false);
        bt_modificar.setEnabled(false);
        bt_eliminar.setEnabled(false);
        bt_registrar.setEnabled(true);
    }

    private void formatoFechas() {
        dc_fecha_entrada.setDateFormatString("dd/MM/yy");
        dc_fecha_salida.setDateFormatString("dd/MM/yy");
    }
    DAOMantenimientoEquipo daoMant = new DAOMantenimientoEquipo();
    DAOEquipoOficina daoEquipo = new DAOEquipoOficina();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_equipo;
    private javax.swing.JComboBox<String> cmb_tipo;
    private com.toedter.calendar.JDateChooser dc_fecha_entrada;
    private com.toedter.calendar.JDateChooser dc_fecha_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_mantenimientos;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
