/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOCamion;
import com.mycompany.transporte_mercancia.Data.DAOMantenimiento;
import com.mycompany.transporte_mercancia.Logica.Camion;
import com.mycompany.transporte_mercancia.Logica.Mantenimiento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmMantenimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmMantenimiento
     */
    public FrmMantenimiento() {
        initComponents();
        cargarTabla();
        cargarComboCamion();
        formatoFechas();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmb_matricula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mantenimientos = new javax.swing.JTable();
        dc_fecha_entrada = new com.toedter.calendar.JDateChooser();
        dc_fecha_salida = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id_mantenciones = new javax.swing.JTextField();
        bt_cerrar_pestaña = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();

        jLabel1.setText("Seleccione el camion");

        jLabel2.setText("Fecha Ingreso");

        jLabel3.setText("Descripcion");

        bt_registrar.setText("Registrar ");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar ");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        tbl_mantenimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_mantenimientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mantenimientosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mantenimientos);

        jLabel4.setText("Fecha salida");

        jLabel5.setText("ID");

        txt_id_mantenciones.setEditable(false);

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(dc_fecha_salida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bt_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bt_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmb_matricula, 0, 93, Short.MAX_VALUE)
                                            .addComponent(txt_id_mantenciones))
                                        .addGap(8, 8, 8)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_actualizar_pestaña)
                .addGap(18, 18, 18)
                .addComponent(bt_cerrar_pestaña)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_id_mantenciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addComponent(dc_fecha_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dc_fecha_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar)
                            .addComponent(bt_modificar))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cerrar_pestaña)
                            .addComponent(bt_actualizar_pestaña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Carga el combo desplegable de matrículas con los camiones disponibles
     * (sin mantenimiento activo) obtenidos desde la base de datos.
     */
    public void cargarComboCamion() {
        DAOCamion dao = new DAOCamion();
        cmb_matricula.removeAllItems();

        for (Camion c : dao.listarDisponibles()) {
            cmb_matricula.addItem(c.getMatricula());
        }
    }

    /**
     * Maneja el evento del botón "Registrar". Construye un objeto
     * {@link Mantenimiento} con los datos del formulario (matrícula, fechas de
     * entrada/salida y descripción) y lo persiste en la base de datos. Al
     * finalizar recarga la tabla, el combo y limpia el formulario.
     *
     * @param evt evento de acción generado por el botón bt_registrar
     */
    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        Mantenimiento m = new Mantenimiento();

        String matricula = (String) this.cmb_matricula.getSelectedItem();
        m.setMatricula(matricula);

        java.util.Date fechaEntrada = dc_fecha_entrada.getDate();
        java.util.Date fechaSalida = dc_fecha_salida.getDate();
        java.sql.Date fechaEntradaSQL = new java.sql.Date(fechaEntrada.getTime());
        java.sql.Date fechaSalidaSQL = new java.sql.Date(fechaSalida.getTime());

        if (!fechaSalidaSQL.after(fechaEntradaSQL)) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de salida debe ser posterior a la fecha de entrada.",
                    "Error de fechas",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        m.setFechaEntrada(fechaEntradaSQL);
        m.setFechaSalida(fechaSalidaSQL);
        m.setDescripcion(this.txt_descripcion.getText());

        dp.create(m);
        cargarTabla();
        cargarComboCamion();
        limpiarFormulario();
    }//GEN-LAST:event_bt_registrarActionPerformed
    /**
     * Maneja el evento de clic sobre la tabla de mantenimientos. Al seleccionar
     * una fila, carga los datos del registro correspondiente en los campos del
     * formulario y activa el modo edición.
     *
     * @param evt evento de ratón generado al hacer clic en la tabla
     */
    private void tbl_mantenimientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mantenimientosMouseClicked
        int selectedRow = this.tbl_mantenimientos.getSelectedRow();
        if (selectedRow != -1) {
            Object cellValue = this.tbl_mantenimientos.getValueAt(selectedRow, 0);
            Integer id_seleccionado = (Integer) cellValue;
            this.txt_id_mantenciones.setText(id_seleccionado.toString());

            for (Mantenimiento m : dp.listarTodos()) {
                if (m.getIdMantenimiento() == id_seleccionado) {
                    dc_fecha_entrada.setDate(new java.util.Date(m.getFechaEntrada().getTime()));
                    dc_fecha_salida.setDate(new java.util.Date(m.getFechaSalida().getTime()));
                    this.txt_descripcion.setText(m.getDescripcion());
                    this.cmb_matricula.setSelectedItem(m.getMatricula());
                }
            }
            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_mantenimientosMouseClicked
    /**
     * Activa el modo edición del formulario habilitando los botones "Cancelar",
     * "Modificar" y "Eliminar", y deshabilitando "Registrar". Se invoca cuando
     * el usuario selecciona un registro existente en la tabla.
     */
    private void activarModoEditar() {
        this.bt_cancelar.setEnabled(true);
        this.bt_modificar.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_registrar.setEnabled(false);
    }

    /**
     * Cambia el formulario a modo nuevo, preparando para registrar una
     * habitación.
     */
    private void activarModoNuevo() {
        this.bt_cancelar.setEnabled(false);
        this.bt_modificar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_registrar.setEnabled(true);
    }

    /**
     * Maneja el evento del botón "Modificar". Construye un objeto
     * {@link Mantenimiento} con el ID del registro seleccionado y los datos
     * actualizados del formulario, luego invoca la actualización en la base de
     * datos. Al finalizar recarga la tabla, el combo, limpia el formulario y
     * regresa al modo nuevo.
     *
     * @param evt evento de acción generado por el botón bt_modificar
     */
    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        Mantenimiento m = new Mantenimiento();
        Integer id_seleccionado = Integer.parseInt(this.txt_id_mantenciones.getText());
        m.setIdMantenimiento(id_seleccionado);

        String matricula = (String) this.cmb_matricula.getSelectedItem();
        m.setMatricula(matricula);

        java.util.Date fechaEntrada = dc_fecha_entrada.getDate();
        java.util.Date fechaSalida = dc_fecha_salida.getDate();
        java.sql.Date fechaEntradaSQL = new java.sql.Date(fechaEntrada.getTime());
        java.sql.Date fechaSalidaSQL = new java.sql.Date(fechaSalida.getTime());

        m.setFechaEntrada(fechaEntradaSQL);
        m.setFechaSalida(fechaSalidaSQL);
        m.setDescripcion(this.txt_descripcion.getText());
        
      
        if (!fechaSalidaSQL.after(fechaEntradaSQL)) {
            JOptionPane.showMessageDialog(this,
                    "La fecha de salida debe ser posterior a la fecha de entrada.",
                    "Error de fechas",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        dp.update(m);
        cargarTabla();
        cargarComboCamion();
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_modificarActionPerformed
    /**
     * Maneja el evento del botón "Eliminar". Busca el registro de mantenimiento
     * cuyo ID coincide con el campo de texto seleccionado, lo elimina de la
     * base de datos y actualiza la tabla. Al finalizar activa el modo nuevo y
     * limpia el formulario.
     *
     * @param evt evento de acción generado por el botón bt_eliminar
     */
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        Integer id_seleccionado = Integer.parseInt(this.txt_id_mantenciones.getText());
        Mantenimiento m_encontrado = new Mantenimiento();
        for (Mantenimiento m : dp.listarTodos()) {
            if (m.getIdMantenimiento() == id_seleccionado) {
                m_encontrado = m;
            }
        }
        dp.delete(m_encontrado.getIdMantenimiento());
        cargarTabla();
        this.activarModoNuevo();
        limpiarFormulario();
    }//GEN-LAST:event_bt_eliminarActionPerformed
    /**
     * Limpia los campos editables del formulario de mantenimiento, vaciando el
     * área de descripción y restableciendo las fechas de entrada y salida a
     * {@code null}.
     */
    private void limpiarFormulario() {

        this.txt_descripcion.setText("");
        dc_fecha_entrada.setDate(null);
        dc_fecha_salida.setDate(null);
    }

    /**
     * Maneja el evento del botón "Cancelar". Limpia el formulario y regresa al
     * modo nuevo, descartando cualquier selección activa.
     *
     * @param evt evento de acción generado por el botón bt_cancelar
     */
    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed
    /**
     * Carga y refresca la tabla de mantenimientos con todos los registros
     * obtenidos desde la base de datos. Define las columnas "id", "Matricula",
     * "Entrada" y "salida", construye el modelo y lo asigna a la {@code JTable}
     * del formulario.
     */
    public void cargarTabla() {

        // 1. Define los datos y encabezados
        Object[] nombresColumnas = {"id", "Matricula", "Entrada", "salida"};

        // 2. Crea el modelo de tabla
        DefaultTableModel modelo = new DefaultTableModel(nombresColumnas, 0);

        // 3. Carga datos desde el arraylist
        for (Mantenimiento m : dp.listarTodos()) {
            Object[] row1 = {m.getIdMantenimiento(), m.getMatricula(), m.getFechaEntrada(), m.getFechaSalida()};
            modelo.addRow(row1); 
        }

        // 4. Establece el modelo de tabla a la JTable
        this.tbl_mantenimientos.setModel(modelo);

    }

    private void formatoFechas() {

        this.dc_fecha_entrada.setDateFormatString("dd/MM/yy");
        this.dc_fecha_salida.setDateFormatString("dd/MM/yy");
    }

    DAOMantenimiento dp = new DAOMantenimiento();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_matricula;
    private com.toedter.calendar.JDateChooser dc_fecha_entrada;
    private com.toedter.calendar.JDateChooser dc_fecha_salida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_mantenimientos;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id_mantenciones;
    // End of variables declaration//GEN-END:variables
}
