/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;
import com.mycompany.transporte_mercancia.Logica.Pieza;
import com.mycompany.transporte_mercancia.Data.DAOPieza;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel; 
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
/**
 *
 * @author Vicente Morales
 */
public class FrmPiezaRepuestos extends javax.swing.JInternalFrame {

    private DAOPieza dao = new DAOPieza();
    private int idSeleccionado = -1;
    
    
    public FrmPiezaRepuestos() {
        initComponents();
        cargarTabla();
        
    tbl_piezas.getSelectionModel().addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            int fila = tbl_piezas.getSelectedRow();
            if (fila == -1) return;

            idSeleccionado = (int) tbl_piezas.getValueAt(fila, 0);
            id_txt.setText(String.valueOf(idSeleccionado));
            nom_txt.setText(tbl_piezas.getValueAt(fila, 1).toString());
            desc_txt.setText(tbl_piezas.getValueAt(fila, 2).toString());
            sto_txt.setText(tbl_piezas.getValueAt(fila, 3).toString());
        }
    });
}
    
    
    
    private void cargarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tbl_piezas.getModel();
    modelo.setRowCount(0);
    ArrayList<Pieza> lista = dao.listarTodos();
    for (Pieza p : lista) {
        modelo.addRow(new Object[]{
            p.getIdPieza(),
            p.getNombre(),
            p.getDescripcion(),
            p.getStock(),
            p.getFechaRegistro()
        });
    }
}
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_piezas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        desc_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sto_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_agregar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();

        tbl_piezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Stock", "Fecha registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_piezas);

        jLabel1.setText("ID:");

        id_txt.setEditable(false);
        id_txt.addActionListener(this::id_txtActionPerformed);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripcion:");

        sto_txt.addActionListener(this::sto_txtActionPerformed);

        jLabel4.setText("Stock:");

        bt_agregar.setText("Agregar");
        bt_agregar.addActionListener(this::bt_agregarActionPerformed);

        bt_editar.setText("Editar");
        bt_editar.addActionListener(this::bt_editarActionPerformed);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(this::bt_eliminarActionPerformed);

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(this::bt_limpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(bt_agregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sto_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(desc_txt)
                                    .addComponent(nom_txt)
                                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(bt_eliminar)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_limpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_editar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(desc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_editar)
                            .addComponent(bt_agregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_limpiar)
                            .addComponent(bt_eliminar))
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void sto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sto_txtActionPerformed

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        String nombre = nom_txt.getText().trim();
String descripcion = desc_txt.getText().trim();
String stock = sto_txt.getText().trim();

// Validar campos vacíos
if (nombre.isEmpty() || stock.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Nombre y Stock son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
}

// Flujo Alterno: verificar si ya existe
Pieza existente = dao.buscarPorNombre(nombre);
if (existente != null) {
    JOptionPane.showMessageDialog(this, "ADVERTENCIA: La pieza \"" + nombre + "\" ya existe.", "Duplicado", JOptionPane.WARNING_MESSAGE);
    return;
}

Pieza nueva = new Pieza();
nueva.setNombre(nombre);
nueva.setDescripcion(descripcion);
nueva.setStock(Integer.parseInt(stock));

boolean ok = dao.create(nueva);
if (ok) {
    JOptionPane.showMessageDialog(this, "Pieza agregada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    cargarTabla();
} else {
    JOptionPane.showMessageDialog(this, "ERROR: El sistema falló al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
       id_txt.setText("");
       nom_txt.setText("");
       desc_txt.setText("");
       sto_txt.setText("");
       idSeleccionado = -1;
       tbl_piezas.clearSelection();
    }//GEN-LAST:event_bt_limpiarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (idSeleccionado == -1) {
    JOptionPane.showMessageDialog(this, "Seleccione una pieza de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
}

int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar esta pieza?", "Confirmar", JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    boolean ok = dao.delete(idSeleccionado);
    if (ok) {
        JOptionPane.showMessageDialog(this, "Pieza eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        cargarTabla();
        bt_limpiar.doClick();
    } else {
        JOptionPane.showMessageDialog(this, "ERROR: No se pudo eliminar. La pieza puede estar en uso.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        if (idSeleccionado == -1) {
    JOptionPane.showMessageDialog(this, "Seleccione una pieza de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
}

String nombre = nom_txt.getText().trim();
String stock = sto_txt.getText().trim();

if (nombre.isEmpty() || stock.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Nombre y Stock son obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
}

Pieza p = new Pieza();
p.setIdPieza(idSeleccionado);
p.setNombre(nombre);
p.setDescripcion(desc_txt.getText().trim());
p.setStock(Integer.parseInt(stock));

dao.update(p);
JOptionPane.showMessageDialog(this, "Pieza actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
cargarTabla();
bt_limpiar.doClick();
    }//GEN-LAST:event_bt_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JTextField desc_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JTextField sto_txt;
    private javax.swing.JTable tbl_piezas;
    // End of variables declaration//GEN-END:variables
}
