/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Data.DAOPersonal;
import com.mycompany.transporte_mercancia.Logica.Personal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saave
 */
public class FrmPersonalCompañia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPersonalCompañia
     */
    public FrmPersonalCompañia() {
        initComponents();
        cargarTabla();
        cargarComboRol();
        activarModoNuevo();
        bt_actualizar_pestaña.addActionListener(e -> cargarTabla());
        bt_cerrar_pestaña.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        txt_contrasena = new javax.swing.JPasswordField();
        cmb_rol = new javax.swing.JComboBox<>();
        bt_registrar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_personal = new javax.swing.JTable();
        bt_cerrar_pestaña = new javax.swing.JButton();
        bt_actualizar_pestaña = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Rut:");

        jLabel4.setText("Contraseña:");

        jLabel5.setText("Rol:");

        txt_id.setEditable(false);

        bt_registrar.setText("Registrar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar");
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        tbl_personal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_personal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_personalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_personal);

        bt_cerrar_pestaña.setBackground(new java.awt.Color(255, 0, 0));
        bt_cerrar_pestaña.setText("X");

        bt_actualizar_pestaña.setBackground(new java.awt.Color(0, 153, 255));
        bt_actualizar_pestaña.setForeground(new java.awt.Color(255, 255, 255));
        bt_actualizar_pestaña.setText("🔄");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_registrar))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_modificar)
                            .addComponent(bt_cancelar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_rol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_actualizar_pestaña)
                .addGap(18, 18, 18)
                .addComponent(bt_cerrar_pestaña)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_registrar)
                            .addComponent(bt_modificar))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_eliminar)
                            .addComponent(bt_cancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_cerrar_pestaña)
                            .addComponent(bt_actualizar_pestaña))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Maneja el evento de clic sobre la tabla de personal. Al seleccionar una
     * fila carga los datos del empleado (nombre, RUT, contraseña y rol) en los
     * campos del formulario y activa el modo edición.
     *
     * @param evt evento de ratón generado al hacer clic en la tabla
     */

    private void tbl_personalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_personalMouseClicked
        int fila = tbl_personal.getSelectedRow();
        if (fila != -1) {
            Integer id = (Integer) tbl_personal.getValueAt(fila, 0);
            txt_id.setText(id.toString());

            for (Personal p : dao.listarTodos()) {
                if (p.getIdPersonal() == id) {
                    txt_nombre.setText(p.getNombre());
                    txt_rut.setText(p.getRut());
                    txt_contrasena.setText(p.getContrasena());
                    cmb_rol.setSelectedItem(p.getRol());
                    break;
                }
            }
            activarModoEditar();
        }
    }//GEN-LAST:event_tbl_personalMouseClicked
    /**
     * Maneja el evento del botón "Registrar". Valida que los campos no estén
     * vacíos, que el RUT tenga formato correcto y que no esté duplicado en la
     * base de datos. Si todas las validaciones pasan, crea un nuevo
     * {@link Personal} y lo persiste. Muestra mensajes de error o confirmación
     * según corresponda.
     *
     * @param evt evento de acción generado por el botón bt_registrar
     */
    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        String rutIngresado = txt_rut.getText().trim();

        if (txt_nombre.getText().isEmpty() || txt_rut.getText().isEmpty()
                || txt_contrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Validar que el nombre solo contenga letras y espacios
        if (!txt_nombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]+")) {
            JOptionPane.showMessageDialog(this,
                    "El nombre solo puede contener letras.",
                    "Nombre inválido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!validarRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this,
                    "El RUT ingresado no es válido.\nEjemplo: 12.345.678-5",
                    "Rut inválido",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

// Validación RUT único
        if (dao.existeRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this,
                    "El RUT ingresado ya existe en el sistema.",
                    "RUT duplicado",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Personal p = new Personal();
        p.setNombre(txt_nombre.getText());
        p.setRut(txt_rut.getText());
        p.setContrasena(txt_contrasena.getText());
        p.setRol((String) cmb_rol.getSelectedItem());

        dao.create(p);
        JOptionPane.showMessageDialog(this, "Personal registrado correctamente.");
        cargarTabla();
        limpiarFormulario();

    }//GEN-LAST:event_bt_registrarActionPerformed
    /**
     * Maneja el evento del botón "Modificar". Construye un objeto
     * {@link Personal} con el ID del registro seleccionado y los datos
     * actualizados, luego invoca la actualización en la base de datos. Al
     * finalizar recarga la tabla, limpia el formulario, activa el modo nuevo y
     * muestra un mensaje de confirmación.
     *
     * @param evt evento de acción generado por el botón bt_modificar
     */
    private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
        String rutIngresado = txt_rut.getText().trim();
        int idSeleccionado = Integer.parseInt(txt_id.getText());

        // 1. Validar campos vacíos
        if (txt_nombre.getText().isEmpty() || txt_rut.getText().isEmpty()
                || txt_contrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.",
                    "Campos vacíos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Validar que el nombre solo contenga letras y espacios
        if (!txt_nombre.getText().trim().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ ]+")) {
            JOptionPane.showMessageDialog(this,
                    "El nombre solo puede contener letras.",
                    "Nombre inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Validar formato y dígito verificador del RUT
        if (!validarRut(rutIngresado)) {
            JOptionPane.showMessageDialog(this,
                    "El RUT ingresado no es válido.\nEjemplo: 12.345.678-5",
                    "Rut inválido", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Verificar duplicado excluyendo el propio registro
        if (dao.existeRut(rutIngresado, idSeleccionado)) {
            JOptionPane.showMessageDialog(this,
                    "El RUT ingresado ya existe en el sistema.",
                    "RUT duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 5. Recién construir y actualizar
        Personal p = new Personal();
        p.setIdPersonal(idSeleccionado);
        p.setNombre(txt_nombre.getText().trim());
        p.setRut(rutIngresado);
        p.setContrasena(txt_contrasena.getText().trim());
        p.setRol((String) cmb_rol.getSelectedItem());

        dao.update(p);
        cargarTabla();
        limpiarFormulario();
        activarModoNuevo();
        JOptionPane.showMessageDialog(this, "Personal actualizado correctamente.");
    }//GEN-LAST:event_bt_modificarActionPerformed
    /**
     * Maneja el evento del botón "Eliminar". Solicita confirmación al usuario
     * mediante un diálogo y, si acepta, elimina el registro cuyo ID está en el
     * campo de texto. Al finalizar recarga la tabla, limpia el formulario y
     * activa el modo nuevo.
     *
     * @param evt evento de acción generado por el botón bt_eliminar
     */
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar este registro?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txt_id.getText());
            dao.delete(id);
            cargarTabla();
            limpiarFormulario();
            activarModoNuevo();
        }
    }//GEN-LAST:event_bt_eliminarActionPerformed
    /**
     * Formatea un RUT eliminando puntos y guión, y lo devuelve con el formato
     * normalizado {@code NUMERO-DV} (en mayúsculas).
     *
     * @param rut RUT en cualquier formato (con o sin puntos y guión)
     * @return RUT formateado como {@code NUMERO-DV}
     */
    public String formatearRut(String rut) {
        rut = rut.replace(".", "").replace("-", "").toUpperCase();
        String numero = rut.substring(0, rut.length() - 1);
        String dv = rut.substring(rut.length() - 1);
        return numero + "-" + dv;
    }

    /**
     * Verifica que el RUT tenga el formato básico {@code NUMERO-DV}, sin
     * validar el dígito verificador.
     *
     * @param rut RUT normalizado (sin puntos)
     * @return {@code true} si el formato es válido; {@code false} en caso
     * contrario
     */
    public boolean validarFormato(String rut) {
        return rut.matches("^[0-9]+-[0-9K]$");
    }

    /**
     * Valida el RUT completo verificando el dígito verificador.
     *
     * @param rut RUT ingresado
     * @return true si el RUT es válido
     */
    public boolean validarRut(String rut) {
        if (rut == null || rut.trim().isEmpty()) {
            return false;
        }

        rut = rut.replace(".", "").replace("-", "").toUpperCase();

        if (!rut.matches("^\\d{7,8}[0-9K]$")) {
            return false;
        }

        String numero = rut.substring(0, rut.length() - 1);  // todo menos DV
        String dvIngresado = rut.substring(rut.length() - 1);

        String dvCalculado = calcularDV(numero);

        return dvIngresado.equals(dvCalculado);
    }

    /**
     * Calcula el dígito verificador (DV) del RUT.
     *
     * @param rut número del RUT sin DV
     * @return dígito verificador calculado
     */
    // Cálculo tradicional del DV
    public String calcularDV(String rut) {
        int suma = 0;
        int multiplicador = 2;

        for (int i = rut.length() - 1; i >= 0; i--) {
            suma += Character.getNumericValue(rut.charAt(i)) * multiplicador;
            multiplicador = (multiplicador == 7) ? 2 : multiplicador + 1;
        }

        int residuo = 11 - (suma % 11);

        if (residuo == 11) {
            return "0";
        }
        if (residuo == 10) {
            return "K";
        }
        return String.valueOf(residuo);
    }

    /**
     * Maneja el evento del botón "Cancelar". Limpia el formulario y regresa al
     * modo nuevo, descartando cualquier selección activa.
     *
     * @param evt evento de acción generado por el botón bt_cancelar
     */
    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        limpiarFormulario();
        activarModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed
    /**
     * Carga el combo desplegable de roles con los tres perfiles disponibles en
     * el sistema: {@code jefe_flota}, {@code admin_mantenimiento} y
     * {@code admin_jefe}.
     */
    private void cargarComboRol() {
        cmb_rol.removeAllItems();
        cmb_rol.addItem("jefe_flota");
        cmb_rol.addItem("admin_mantenimiento");
        cmb_rol.addItem("admin_jefe");
        cmb_rol.addItem("admin_equipos");
        cmb_rol.addItem("tecnico_mantenimiento_equipos");
        cmb_rol.addItem("tecnico_it");
        cmb_rol.addItem("admin_mantenimiento_equipos");
        cmb_rol.addItem("admin_inventario");
    }

    /**
     * Carga y refresca la tabla de personal con todos los registros obtenidos
     * desde la base de datos. Define las columnas "ID", "Nombre", "RUT" y
     * "Rol", construye el modelo y lo asigna a la {@code JTable} del
     * formulario.
     */
    public void cargarTabla() {
        Object[] columnas = {"ID", "Nombre", "RUT", "Rol"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

        for (Personal p : dao.listarTodos()) {
            Object[] fila = {p.getIdPersonal(), p.getNombre(), p.getRut(), p.getRol()};
            modelo.addRow(fila);
        }
        tbl_personal.setModel(modelo);
    }

    /**
     * Limpia todos los campos editables del formulario de personal, vaciando
     * los textos y restableciendo el combo de rol al primer elemento.
     */
    private void limpiarFormulario() {
        txt_id.setText("");
        txt_nombre.setText("");
        txt_rut.setText("");
        txt_contrasena.setText("");
        cmb_rol.setSelectedIndex(0);
    }

    /**
     * Activa el modo edición del formulario: deshabilita "Registrar" y habilita
     * "Modificar", "Eliminar" y "Cancelar". Se invoca cuando el usuario
     * selecciona una fila en la tabla.
     */
    private void activarModoEditar() {
        bt_registrar.setEnabled(false);
        bt_modificar.setEnabled(true);
        bt_eliminar.setEnabled(true);
        bt_cancelar.setEnabled(true);
    }

    /**
     * Activa el modo nuevo del formulario: habilita "Registrar" y deshabilita
     * "Modificar", "Eliminar" y "Cancelar". Se invoca al inicializar el
     * formulario, cancelar o completar una operación.
     */
    private void activarModoNuevo() {
        bt_registrar.setEnabled(true);
        bt_modificar.setEnabled(false);
        bt_eliminar.setEnabled(false);
        bt_cancelar.setEnabled(false);
    }
    /**
     * Instancia del DAO de personal utilizada para las operaciones CRUD.
     */
    DAOPersonal dao = new DAOPersonal();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_actualizar_pestaña;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar_pestaña;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_personal;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
