/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import com.mycompany.transporte_mercancia.Logica.Pieza;
import com.mycompany.transporte_mercancia.Data.DAOPieza;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Vicente Morales
 */
/**
 * Formulario CRUD de Piezas / Repuestos (RF-09).
 *
 * Componentes que deben existir en el Designer de NetBeans: - cod_txt
 * (JTextField) + JLabel "Código" ← NUEVO - nom_txt (JTextField) + JLabel
 * "Nombre" - desc_txt (JTextField) + JLabel "Descripción" - sto_txt
 * (JTextField) + JLabel "Stock" - id_txt (JTextField, no editable, oculto o con
 * JLabel "ID") - tbl_piezas (JTable) dentro de jScrollPane1 - bt_agregar,
 * bt_editar, bt_eliminar, bt_limpiar (JButton)
 */
public class FrmPiezaRepuestos extends javax.swing.JInternalFrame {

    private final DAOPieza dao = new DAOPieza();
    private int idSeleccionado = -1;

    // -------------------------------------------------------
    // CONSTRUCTOR
    // -------------------------------------------------------
    public FrmPiezaRepuestos() {
        initComponents();
        aplicarEstilos();
        configurarTabla();
        cargarTabla();
        activarModoNuevo();

        // Listener de selección en tabla
        tbl_piezas.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tbl_piezas.getSelectedRow();
                if (fila == -1) {
                    return;
                }

                // Índices: 0=id, 1=codigo, 2=nombre, 3=descripcion, 4=stock
                idSeleccionado = (int) tbl_piezas.getValueAt(fila, 0);
                id_txt.setText(String.valueOf(idSeleccionado));
                cod_txt.setText(tbl_piezas.getValueAt(fila, 1).toString());
                nom_txt.setText(tbl_piezas.getValueAt(fila, 2).toString());

                Object desc = tbl_piezas.getValueAt(fila, 3);
                desc_txt.setText(desc != null ? desc.toString() : "");

                sto_txt.setText(tbl_piezas.getValueAt(fila, 4).toString());
            }
            activarModoEditar();
        });
    }

    // -------------------------------------------------------
    // CONFIGURAR COLUMNAS DE LA TABLA
    // -------------------------------------------------------
    /**
     * Define el modelo de la tabla con las columnas correctas. La columna ID
     * (índice 0) se oculta fijando su ancho a 0.
     */
    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"ID", "Código", "Nombre", "Descripción", "Stock", "Fecha Registro"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_piezas.setModel(modelo);

        // Ocultar columna ID
        tbl_piezas.getColumnModel().getColumn(0).setMinWidth(0);
        tbl_piezas.getColumnModel().getColumn(0).setMaxWidth(0);
        tbl_piezas.getColumnModel().getColumn(0).setWidth(0);
    }

    // -------------------------------------------------------
    // CARGAR TABLA
    // -------------------------------------------------------
    private void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_piezas.getModel();
        modelo.setRowCount(0);

        ArrayList<Pieza> lista = dao.listarTodos();
        for (Pieza p : lista) {
            modelo.addRow(new Object[]{
                p.getIdPieza(), // col 0 – oculta
                p.getCodigo(), // col 1
                p.getNombre(), // col 2
                p.getDescripcion(), // col 3
                p.getStock(), // col 4
                p.getFechaRegistro() // col 5
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_piezas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom_txt = new javax.swing.JTextField();
        desc_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sto_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_agregar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_limpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cod_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        tbl_piezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Stock", "Fecha registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_piezas);

        jLabel1.setText("ID:");

        id_txt.setEditable(false);
        id_txt.addActionListener(this::id_txtActionPerformed);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripcion:");

        sto_txt.addActionListener(this::sto_txtActionPerformed);

        jLabel4.setText("Stock:");

        bt_agregar.setText("Agregar");
        bt_agregar.addActionListener(this::bt_agregarActionPerformed);

        bt_editar.setText("Editar");
        bt_editar.addActionListener(this::bt_editarActionPerformed);

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(this::bt_eliminarActionPerformed);

        bt_limpiar.setText("Limpiar");
        bt_limpiar.addActionListener(this::bt_limpiarActionPerformed);

        jLabel5.setText("Codigo:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("🔄");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(desc_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(sto_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(cod_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(nom_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addComponent(id_txt)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bt_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(bt_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(73, 73, 73)
                            .addComponent(bt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cod_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(desc_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sto_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_editar)
                    .addComponent(bt_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_limpiar)
                    .addComponent(bt_eliminar))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_txtActionPerformed

    private void sto_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sto_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sto_txtActionPerformed

    private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
        String codigo = cod_txt.getText().trim();
        String nombre = nom_txt.getText().trim();
        String descripcion = desc_txt.getText().trim();
        String stockTxt = sto_txt.getText().trim();

        // Validar obligatorios
        if (codigo.isEmpty() || nombre.isEmpty() || stockTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Código, Nombre y Stock son obligatorios.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Flujo alterno: código duplicado
        if (dao.buscarPorCodigo(codigo) != null) {
            JOptionPane.showMessageDialog(this,
                    "ADVERTENCIA: Ya existe una pieza con el código \"" + codigo + "\".",
                    "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Flujo alterno: nombre duplicado
        if (dao.buscarPorNombre(nombre) != null) {
            JOptionPane.showMessageDialog(this,
                    "ADVERTENCIA: Ya existe una pieza con el nombre \"" + nombre + "\".",
                    "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int stock;
        try {
            stock = Integer.parseInt(stockTxt);
            if (stock < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El stock debe ser un número entero mayor o igual a 0.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Pieza nueva = new Pieza();
        nueva.setCodigo(codigo);
        nueva.setNombre(nombre);
        nueva.setDescripcion(descripcion);
        nueva.setStock(stock);
        

        if (dao.create(nueva)) {
            JOptionPane.showMessageDialog(this,
                    "Pieza agregada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarTabla();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this,
                    "ERROR: El sistema falló al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_agregarActionPerformed

    private void bt_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limpiarActionPerformed
        limpiar();
        activarModoNuevo();
    }//GEN-LAST:event_bt_limpiarActionPerformed

    /**
     * Limpia el formulario y deselecciona la tabla.
     */
    private void limpiar() {
        id_txt.setText("");
        cod_txt.setText("");
        nom_txt.setText("");
        desc_txt.setText("");
        sto_txt.setText("");
        idSeleccionado = -1;
        tbl_piezas.clearSelection();
    }
    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (idSeleccionado == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una pieza de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar esta pieza?", "Confirmar", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (dao.delete(idSeleccionado)) {
                JOptionPane.showMessageDialog(this,
                        "Pieza eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarTabla();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this,
                        "ERROR: No se pudo eliminar. La pieza puede estar en uso.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        activarModoNuevo();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        if (idSeleccionado == -1) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una pieza de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigo = cod_txt.getText().trim();
        String nombre = nom_txt.getText().trim();
        String stockTxt = sto_txt.getText().trim();

        if (codigo.isEmpty() || nombre.isEmpty() || stockTxt.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Código, Nombre y Stock son obligatorios.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que el código no lo use OTRA pieza
        Pieza porCodigo = dao.buscarPorCodigo(codigo);
        if (porCodigo != null && porCodigo.getIdPieza() != idSeleccionado) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe otra pieza con el código \"" + codigo + "\".",
                    "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que el nombre no lo use OTRA pieza
        Pieza porNombre = dao.buscarPorNombre(nombre);
        if (porNombre != null && porNombre.getIdPieza() != idSeleccionado) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe otra pieza con el nombre \"" + nombre + "\".",
                    "Duplicado", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int stock;
        try {
            stock = Integer.parseInt(stockTxt);
            if (stock < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "El stock debe ser un número entero mayor o igual a 0.",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Pieza p = new Pieza();
        p.setIdPieza(idSeleccionado);
        p.setCodigo(codigo);
        p.setNombre(nombre);
        p.setDescripcion(desc_txt.getText().trim());
        p.setStock(stock);

        dao.update(p);
        JOptionPane.showMessageDialog(this,
                "Pieza actualizada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        cargarTabla();
        limpiar();
        activarModoNuevo();
    }//GEN-LAST:event_bt_editarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

     /**
     * Activa el modo edición en el formulario, habilitando los botones de
     * cancelar, modificar y eliminar, y deshabilitando el botón de registrar.
     */
    private void activarModoEditar() {
        this.bt_limpiar.setEnabled(true);
        this.bt_editar.setEnabled(true);
        this.bt_eliminar.setEnabled(true);
        this.bt_agregar.setEnabled(false);
    }

    /**
     * Activa el modo nuevo para ingresar un equipo.
     */
    private void activarModoNuevo() {
        this.bt_limpiar.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_eliminar.setEnabled(false);
        this.bt_agregar.setEnabled(true);
    }
    
    private void aplicarEstilos() {

        // ── Colores base ─────────────────────────────────────────────────────
        java.awt.Color BG_DARK   = new java.awt.Color(0x0A192F);
        java.awt.Color BG_MID    = new java.awt.Color(0x172A45);
        java.awt.Color BG_FIELD  = new java.awt.Color(0x1F3460);
        java.awt.Color MINT      = new java.awt.Color(0x64FFDA);
        java.awt.Color CYAN      = new java.awt.Color(0x57CBF2);
        java.awt.Color CORAL     = new java.awt.Color(0xFF6B6B);
        java.awt.Color GRAY_BTN  = new java.awt.Color(0x8892B0);
        java.awt.Color TEXT_MAIN = new java.awt.Color(0xCCD6F6);
        java.awt.Color ROW_ALT   = new java.awt.Color(0x112240);

        // ── Fuentes ──────────────────────────────────────────────────────────
        java.awt.Font FONT_LABEL  = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
        java.awt.Font FONT_FIELD  = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13);
        java.awt.Font FONT_BTN    = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  12);
        java.awt.Font FONT_TITLE  = new java.awt.Font("Segoe UI", java.awt.Font.BOLD,  14);

        // ── Panel principal ──────────────────────────────────────────────────
        getContentPane().setBackground(BG_DARK);

        // ── Título del InternalFrame ─────────────────────────────────────────
        setTitle("🔩  Piezas / Repuestos");
        setBackground(BG_MID);

        // ── Labels ───────────────────────────────────────────────────────────
        javax.swing.JLabel[] labels = { jLabel1, jLabel2, jLabel3, jLabel4, jLabel5 };
        for (javax.swing.JLabel lbl : labels) {
            if (lbl != null) {
                lbl.setForeground(TEXT_MAIN);
                lbl.setFont(FONT_LABEL);
            }
        }

        // ── TextFields ───────────────────────────────────────────────────────
        javax.swing.JTextField[] fields = { cod_txt, nom_txt, desc_txt, sto_txt };
        for (javax.swing.JTextField tf : fields) {
            if (tf != null) {
                tf.setBackground(BG_FIELD);
                tf.setForeground(TEXT_MAIN);
                tf.setCaretColor(MINT);
                tf.setFont(FONT_FIELD);
                tf.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createLineBorder(MINT, 1, true),
                    javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
                ));
            }
        }

        // ── Campo ID (solo lectura / oculto visualmente) ─────────────────────
        if (id_txt != null) {
            id_txt.setBackground(BG_MID);
            id_txt.setForeground(GRAY_BTN);
            id_txt.setFont(FONT_FIELD);
            id_txt.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(BG_MID, 1),
                javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
            ));
        }

        // ── Botones con código de color ───────────────────────────────────────
        //   bt_agregar  → menta (acción principal)
        //   bt_editar   → celeste (modificar)
        //   bt_eliminar → coral  (peligro)
        //   bt_limpiar  → gris   (neutral)
        //   jButton2    → celeste (actualizar)
        //   jButton1    → coral  (cerrar)
        estilizarBoton(bt_agregar,  MINT,     BG_DARK,  "+ Agregar",    FONT_BTN);
        estilizarBoton(bt_editar,   CYAN,     BG_DARK,  "# Editar",      FONT_BTN);
        estilizarBoton(bt_eliminar, CORAL,    BG_DARK,  "X Eliminar",    FONT_BTN);
        estilizarBoton(bt_limpiar,  GRAY_BTN, BG_DARK,  "* Limpiar",     FONT_BTN);
        estilizarBoton(jButton2,    CYAN,     BG_DARK,  "🔄 Actualizar",  FONT_BTN);
        estilizarBoton(jButton1,    CORAL,    BG_DARK,  "X Cerrar",      FONT_BTN);

        // ── Tabla ────────────────────────────────────────────────────────────
        tbl_piezas.setBackground(BG_MID);
        tbl_piezas.setForeground(TEXT_MAIN);
        tbl_piezas.setFont(FONT_FIELD);
        tbl_piezas.setRowHeight(26);
        tbl_piezas.setGridColor(new java.awt.Color(0x1F3460));
        tbl_piezas.setSelectionBackground(MINT);
        tbl_piezas.setSelectionForeground(BG_DARK);
        tbl_piezas.setShowHorizontalLines(true);
        tbl_piezas.setShowVerticalLines(false);

        // Cabecera de tabla
        javax.swing.table.JTableHeader header = tbl_piezas.getTableHeader();
        header.setBackground(BG_MID);
        header.setForeground(MINT);
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
        ((javax.swing.table.DefaultTableCellRenderer) header.getDefaultRenderer())
            .setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Renderer con filas alternas
        tbl_piezas.setDefaultRenderer(Object.class,
            new javax.swing.table.DefaultTableCellRenderer() {
                @Override
                public java.awt.Component getTableCellRendererComponent(
                        javax.swing.JTable table, Object value, boolean isSelected,
                        boolean hasFocus, int row, int column) {
                    super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    if (isSelected) {
                        setBackground(MINT);
                        setForeground(BG_DARK);
                    } else {
                        setBackground(row % 2 == 0 ? BG_MID : ROW_ALT);
                        setForeground(TEXT_MAIN);
                    }
                    setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 8));
                    return this;
                }
            }
        );

        // ── ScrollPane ───────────────────────────────────────────────────────
        jScrollPane1.setBackground(BG_DARK);
        jScrollPane1.getViewport().setBackground(BG_MID);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(0x1F3460), 1));
    }

    /**
     * Aplica estilo visual uniforme a un JButton.
     * @param btn     Botón a estilizar
     * @param bg      Color de fondo
     * @param fg      Color de texto
     * @param texto   Texto/icono del botón
     * @param fuente  Fuente a usar
     */
    private void estilizarBoton(javax.swing.JButton btn,
                                java.awt.Color bg,
                                java.awt.Color fg,
                                String texto,
                                java.awt.Font fuente) {
        if (btn == null) return;
        btn.setText(texto);
        btn.setBackground(bg);
        btn.setForeground(fg);
        btn.setFont(fuente);
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
        btn.setOpaque(true);
        btn.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
        btn.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(bg.darker(), 1, true),
            javax.swing.BorderFactory.createEmptyBorder(6, 14, 6, 14)
        ));
        // Efecto hover
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override public void mouseEntered(java.awt.event.MouseEvent e) {
                btn.setBackground(bg.brighter());
            }
            @Override public void mouseExited(java.awt.event.MouseEvent e) {
                btn.setBackground(bg);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_limpiar;
    private javax.swing.JTextField cod_txt;
    private javax.swing.JTextField desc_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_txt;
    private javax.swing.JTextField sto_txt;
    private javax.swing.JTable tbl_piezas;
    // End of variables declaration//GEN-END:variables
}
