/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.transporte_mercancia.GUI;

import javax.swing.JFrame;

/**
 * Ventana principal de la aplicación de Transporte de Mercancía. Actúa como
 * contenedor MDI ({@code JDesktopPane}) para los distintos formularios del
 * sistema. Controla la visibilidad de los elementos del menú según el rol del
 * personal autenticado y gestiona el cierre de sesión.
 *
 * @author saave
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Personal que inició sesión en la aplicación.
     */
    private com.mycompany.transporte_mercancia.Logica.Personal personalActivo;

    /**
     * Rol del personal autenticado, usado para aplicar permisos en el menú.
     */
    private String rolActivo;

    /**
     * Crea y configura la ventana principal del sistema. Maximiza la ventana,
     * almacena el personal activo, aplica los permisos de menú según el rol y
     * agrega la opción de cerrar sesión.
     *
     * @param personal objeto
     * {@link com.mycompany.transporte_mercancia.Logica.Personal}
     * correspondiente al usuario autenticado
     */
    public Principal(com.mycompany.transporte_mercancia.Logica.Personal personal) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.personalActivo = personal;
        this.rolActivo = personal.getRol();
        aplicarPermisos();
        agregarMenuCerrarSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editMenu.setText("Registros");

        cutMenuItem.setText("Kilometraje");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        pasteMenuItem.setText("Camiones");
        pasteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(pasteMenuItem);

        jMenuItem1.setText("Conductores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem1);

        jMenuItem3.setText("Personal Compañia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem3);

        jMenuItem4.setText("Equipos de Oficina");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem4);

        jMenuItem8.setText("Software");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem8);

        jMenuItem9.setText("Piezas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem9);

        jMenuItem10.setText("Asignar Software");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem10);

        menuBar.add(editMenu);

        jMenu1.setText("Mantenimientos");

        jMenuItem2.setText("Camiones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setText("Equipos de oficina");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        menuBar.add(jMenu1);

        jMenu2.setText("Consultas");

        jMenuItem7.setText("Mantenimiento Equipos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Agrega dinámicamente al menú principal un elemento "Sesión" con la opción
     * "🔒 Cerrar Sesión". Al activarse, cierra la ventana actual y redirige al
     * formulario de login ({@link FrmLogin}).
     */
    private void agregarMenuCerrarSesion() {
        javax.swing.JMenu menuSesion = new javax.swing.JMenu("Sesión");
        javax.swing.JMenuItem itemCerrar = new javax.swing.JMenuItem("🔒 Cerrar Sesión");

        itemCerrar.addActionListener(e -> {
            new FrmLogin().setVisible(true);
            this.dispose();
        });

        menuSesion.add(itemCerrar);
        menuBar.add(menuSesion);
    }

    /**
     * Aplica los permisos de visibilidad del menú según el rol del usuario
     * autenticado. Primero oculta todos los ítems y luego habilita solo los que
     * corresponden al rol:
     * <ul>
     * <li>{@code conductor} — Kilometraje</li>
     * <li>{@code jefe_flota} — Camiones, Conductores</li>
     * <li>{@code admin_mantenimiento} — Mantenimiento</li>
     * <li>{@code admin_jefe} — todos los módulos</li>
     * </ul>
     */
    private void aplicarPermisos() {
        cutMenuItem.setVisible(false);    // Kilometraje
        pasteMenuItem.setVisible(false);  // Camiones
        jMenuItem1.setVisible(false);     // Conductores
        jMenuItem2.setVisible(false);     // MantenimientoCamiones
        jMenuItem3.setVisible(false);     // Personal
        jMenuItem4.setVisible(false);     //equiposOfcina
        jMenuItem5.setVisible(false);     //mantenimientoEquipos
        jMenuItem7.setVisible(false);     //ConsultaMantenimientoEquipos
        jMenuItem8.setVisible(false);     //software
        jMenuItem9.setVisible(false);     //Repuestos
        jMenuItem10.setVisible(false);    //AsignarSoftware

        switch (rolActivo) {
            case "conductor":
                cutMenuItem.setVisible(true);
                break;
            case "jefe_flota":
                pasteMenuItem.setVisible(true);
                jMenuItem1.setVisible(true);
                break;
            case "admin_mantenimiento":
                jMenuItem2.setVisible(true);
                jMenuItem5.setVisible(true);
                break;
            case "admin_jefe":
                cutMenuItem.setVisible(true);
                pasteMenuItem.setVisible(true);
                jMenuItem1.setVisible(true);
                jMenuItem2.setVisible(true);
                jMenuItem3.setVisible(true);
                jMenuItem4.setVisible(true);
                jMenuItem5.setVisible(true);
                jMenuItem7.setVisible(true);     
                jMenuItem8.setVisible(true); 
                jMenuItem9.setVisible(true);    
                jMenuItem10.setVisible(true);   
                break;
            case "admin_equipos":
                jMenuItem4.setVisible(true);
                break;
                
            case "tecnico_mantenimiento_equipos":
                jMenuItem5.setVisible(true);
                break;
            case "tecnico_it":
                jMenuItem8.setVisible(true); 
                jMenuItem10.setVisible(true);  
                break;
                
            case "admin_mantenimiento_equipos":
                jMenuItem7.setVisible(true);  
                break;
            case "admin_inventario":
                jMenuItem9.setVisible(true);  
                break;

        }
    }

    /**
     * Abre el formulario {@link FrmKilometraje} dentro del panel de escritorio,
     * pasando el personal activo para filtrar los registros según el rol.
     *
     * @param evt evento de acción generado por el ítem de menú "Kilometraje"
     */
    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        FrmKilometraje r = new FrmKilometraje(personalActivo);
        this.desktopPane.add(r);
        r.setSize(800, 500);
        r.setVisible(true);


    }//GEN-LAST:event_cutMenuItemActionPerformed
    /**
     * Abre el formulario {@link FrmCamiones} dentro del panel de escritorio
     * para la gestión del inventario de camiones.
     *
     * @param evt evento de acción generado por el ítem de menú "Camiones"
     */

    private void pasteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteMenuItemActionPerformed
        FrmCamiones r = new FrmCamiones();
        this.desktopPane.add(r);
        r.setSize(911, 592);
        r.setVisible(true);

    }//GEN-LAST:event_pasteMenuItemActionPerformed
    /**
     * Abre el formulario {@link FrmConductores} dentro del panel de escritorio
     * para la gestión del personal de conducción.
     *
     * @param evt evento de acción generado por el ítem de menú "Conductores"
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmConductores r = new FrmConductores();
        this.desktopPane.add(r);
        r.setSize(905, 623);
        r.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * Abre el formulario {@link FrmMantenimiento} dentro del panel de
     * escritorio para el registro y gestión de mantenimientos de camiones.
     *
     * @param evt evento de acción generado por el ítem de menú "Mantenimiento"
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmMantenimiento r = new FrmMantenimiento();
        this.desktopPane.add(r);
        r.setSize(996, 629);
        r.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed
    /**
     * Abre el formulario {@link FrmPersonalCompañia} dentro del panel de
     * escritorio para la administración del personal de la compañía.
     *
     * @param evt evento de acción generado por el ítem de menú "Personal"
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmPersonalCompañia frm = new FrmPersonalCompañia();
        this.desktopPane.add(frm);
        frm.setSize(858, 595);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmEquiposDeOficina frm = new FrmEquiposDeOficina();
        this.desktopPane.add(frm);
        frm.setSize(890, 620);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        FrmMantenimientoEquipos frm = new FrmMantenimientoEquipos();
        this.desktopPane.add(frm);
        frm.setSize(1470, 1050);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmConsultaMantenimientoEquipos frm = new FrmConsultaMantenimientoEquipos();
        this.desktopPane.add(frm);
        frm.setSize(865, 540);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FmrSoftware frm = new FmrSoftware();
        this.desktopPane.add(frm);
        frm.setSize(870, 590);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FrmPiezaRepuestos frm = new FrmPiezaRepuestos();
        this.desktopPane.add(frm);
        frm.setSize(900, 520);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrmAsignarSoftware frm = new FrmAsignarSoftware();
        this.desktopPane.add(frm);
        frm.setSize(940, 640);
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * Punto de entrada de la aplicación. Configura el Look and Feel Nimbus (si
     * está disponible) y lanza el formulario de login en el hilo de eventos de
     * Swing ({@code EventQueue}).
     *
     * @param args argumentos de línea de comandos (no utilizados)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
